export default {
  id: 'CA',
  labelKey: 'onboarding.steps.countryCA',
  currency: 'CAD',
  symbol: '$',
  distanceUnit: 'km',
  taxInstallmentDates: [
    { month: 3, day: 15, label: 'Q1 instalment' },
    { month: 6, day: 15, label: 'Q2 instalment' },
    { month: 9, day: 15, label: 'Q3 instalment' },
    { month: 12, day: 15, label: 'Q4 instalment' },
  ],
  hasCPP: true,
  hasHST: true,
  mileageRateSource: 'CRA',
  tax: {
    taxInstallmentReminderDays: 10,
    hstOnboarding: true,
    intlLocaleTag: 'en-CA',
    defaultWithholdingPct: 28,
    regionPresetType: 'CA',
    fallbackCurrency: 'CAD',
    hstRateWhenRegistered: 0.13,
    calcCpp: true,
    calcSeTax: false,
    stdMileageChoice: 'CRA',
    regionLabel: 'province',
    secondaryEstimator: 'cpp',
    footnote: 'canada',
    defaultRegionCode: 'ON',
  },
};
