export default {
  id: 'UK',
  labelKey: 'onboarding.steps.countryUK',
  currency: 'GBP',
  symbol: '£',
  distanceUnit: 'mi',
  taxInstallmentDates: [
    { month: 1, day: 31, label: 'Payment on account (balancing)' },
    { month: 7, day: 31, label: 'Payment on account' },
  ],
  mileageRateSource: '',
  tax: {
    taxInstallmentReminderDays: 10,
    hstOnboarding: false,
    intlLocaleTag: 'en-GB',
    defaultWithholdingPct: 25,
    regionPresetType: null,
    fallbackCurrency: 'GBP',
    hstRateWhenRegistered: 0,
    calcCpp: false,
    calcSeTax: false,
    stdMileageChoice: 'SIMPLE',
    regionLabel: 'state',
    secondaryEstimator: 'none',
    footnote: 'generic',
    defaultRegionCode: '',
  },
};
