export default {
  id: 'US',
  labelKey: 'onboarding.steps.countryUS',
  currency: 'USD',
  symbol: '$',
  distanceUnit: 'mi',
  taxInstallmentDates: [
    { month: 4, day: 15, label: 'Q1 estimated tax' },
    { month: 6, day: 15, label: 'Q2 estimated tax' },
    { month: 9, day: 15, label: 'Q3 estimated tax' },
    { month: 1, day: 15, label: 'Q4 estimated tax', followYear: true },
  ],
  hasSETax: true,
  mileageRateSource: 'IRS',
  tax: {
    taxInstallmentReminderDays: 10,
    hstOnboarding: false,
    intlLocaleTag: 'en-US',
    defaultWithholdingPct: 25,
    regionPresetType: 'US',
    fallbackCurrency: 'USD',
    hstRateWhenRegistered: 0,
    calcCpp: false,
    calcSeTax: true,
    stdMileageChoice: 'IRS',
    regionLabel: 'state',
    secondaryEstimator: 'se',
    footnote: 'us',
    defaultRegionCode: 'CA',
  },
};
