/**
 * All user-facing copy (Feature 258 — `fr` mirrors `en` keys exactly).
 *
 * F7 structure: app, common, onboarding, shifts, analytics, notifications, errors,
 * vehicles, expenses, platforms, tax, goals, settings, reports, schedule, search,
 * plus `modules` / `views` / `ui` placeholders aligned to `plan.md` file tree and F8 shell.
 * Leaf values are always strings so `t('a.b.c')` resolves to a string (fallback: English, then key).
 * Module-specific marketing copy and long-form help: Phase 2+ modules will replace placeholder text.
 */

/** @type {Record<'en'|'fr', Record<string, unknown>>} */
export const strings = {
  en: {
    app: {
      name: 'Macadam',
      tagline: 'Gig earnings, local-first',
      updateAvailable: 'App updated — reload for latest version',
      reload: 'Reload',
      offlineBanner: 'You are offline. Changes sync when you reconnect.',
      online: 'Online',
      offline: 'Offline',
      navDashboard: 'Dashboard',
      navShifts: 'Shifts',
      navAnalytics: 'Analytics',
      navGoals: 'Goals',
      navSettings: 'Settings',
      navTax: 'Tax',
      navVehicles: 'Vehicles',
      navSchedule: 'Schedule',
      navReports: 'Reports',
      navSearch: 'Search',
      navMore: 'More',
      platformAll: 'All',
      headerAria: 'App header',
      navAria: 'Main navigation',
      skipToContent: 'Skip to main content',
    },
    common: {
      save: 'Save',
      cancel: 'Cancel',
      close: 'Close',
      confirm: 'Confirm',
      all: 'All',
      sort: 'Sort',
      delete: 'Delete',
      edit: 'Edit',
      done: 'Done',
      back: 'Back',
      next: 'Next',
      loading: 'Loading…',
      optional: 'Optional',
      required: 'Required',
      yes: 'Yes',
      no: 'No',
      copy: 'Copy',
      share: 'Share',
      retry: 'Retry',
    },
    onboarding: {
      title: 'Welcome to Macadam',
      subtitle: 'Track gig earnings in one place',
      continue: 'Continue',
      skip: 'Skip for now',
      finish: 'Get started',
      stepProgress: 'Step {current} of {total}',
      welcomeTitle: 'Welcome',
      platformsTitle: 'Your platforms',
      vehicleTitle: 'Your vehicle',
      goalsTitle: 'Weekly goal',
      notificationsTitle: 'Stay on track',
      privacyTitle: 'Privacy',
      summaryTitle: 'You are set',
      placeholderBody:
        'Onboarding step copy is finalized in Phase 2 (orchestrator + steps.js). Keys exist so `t()` stays stable.',
      tryDemo: 'Try demo first',
      demoEnabled: 'Demo mode on — sample-friendly nudges are enabled.',
      resumeTitle: 'Continue setup?',
      resumeMessage: 'You started onboarding earlier this session. Continue where you left off, or start over.',
      resumeContinue: 'Continue',
      resumeStartOver: 'Start over',
      completeToast: 'Your vault is ready. Welcome aboard!',
      exportDone: 'Setup file downloaded.',
      resetNeedExport: 'Export a backup before resetting the vault.',
      resetTitle: 'Reset vault',
      resetMessage: 'This deletes all local Macadam data on this device. Export a backup first.',
      resetConfirm: 'Reset everything',
      motivation: {
        high: 'Strong target — we will cheer you on every week.',
        mid: 'Solid goal — great balance of stretch and realism.',
        low: 'Gentle ramp — you can raise it anytime in Goals.',
        start: 'Every journey starts with a single shift logged.',
      },
      schedule: {
        flexible: 'Flexible hours',
        weekdays: 'Mostly weekdays',
        evenings: 'Evenings',
        weekends: 'Weekends',
      },
      theme: { light: 'Light', dark: 'Dark', auto: 'Auto' },
      vehicleTypes: {
        gas: 'Gas vehicle',
        hybrid: 'Hybrid',
        ev: 'Electric',
        motorcycle: 'Motorcycle',
        bicycle: 'Bicycle',
        ebike: 'E-bike',
        scooter: 'Scooter',
        walking: 'Walking',
      },
      steps: {
        platformsTitle: 'Where do you drive?',
        platformsLead: 'Pick every platform you use. You can change this later.',
        profileTitle: 'How should we greet you?',
        profileLead: 'This name appears on your dashboard and exports.',
        driverName: 'Your name',
        avatarPick: 'Avatar',
        avatarInitials: 'Use initials',
        avatarCustom: 'Upload a photo',
        avatarUpload: 'Choose image',
        regionTitle: 'Country or region',
        regionLead: 'We set currency, distance defaults, and tax hints from here.',
        country: 'Country',
        countryCA: 'Canada',
        countryUS: 'United States',
        countryUK: 'United Kingdom',
        currencyHint: 'Currency',
        vehicleTitle: 'Primary vehicle',
        vehicleLead: 'Fuel or EV details unlock smarter cost estimates later.',
        vehicleNickname: 'Nickname',
        vehicleType: 'Vehicle type',
        make: 'Make',
        model: 'Model',
        year: 'Year',
        secondVehicleTitle: 'Another vehicle?',
        secondVehicleLead: 'Optional — useful if you switch between car and bike.',
        addAnotherVehicle: 'Add a second vehicle',
        homeBaseTitle: 'Home base zone',
        homeBaseLead: 'A short label for the area you usually start from.',
        homeBaseLabel: 'Zone label',
        homeBasePlaceholder: 'e.g. Downtown, North End',
        scheduleTitle: 'Typical schedule',
        scheduleLead: 'Helps with reminders and planning views.',
        weeklyGoalTitle: 'Weekly earnings goal',
        weeklyGoalLead: 'We use this for the goal ring and weekly nudges.',
        weeklyGoalLabel: 'Target gross per week',
        longTermGoalsTitle: 'Monthly and annual targets',
        longTermGoalsLead: 'Prefilled from your weekly goal — adjust freely.',
        monthlyGoal: 'Monthly target',
        annualGoal: 'Annual target',
        taxTitle: 'Tax set-aside',
        taxLead: 'Rough percentage to set aside from gross for taxes.',
        province: 'Province or territory',
        state: 'State',
        taxRegionPlaceholder: 'Select…',
        taxWithholding: 'Withholding %',
        applyPreset: 'Apply region preset',
        hstTitle: 'GST / HST registration',
        hstLead: 'Canada only — affects HST worksheets later.',
        hstToggle: 'I collect or remit GST / HST',
        hstSkip: 'GST / HST does not apply for your selected country.',
        distanceTitle: 'Distance units',
        distanceLead: 'Shown on shifts, mileage, and maps.',
        unitKm: 'Kilometres',
        unitMi: 'Miles',
        themeTitle: 'Appearance',
        themeLead: 'You can change this anytime in Settings.',
        notifyTitle: 'Notifications',
        notifyLead: 'All local — we never upload your shifts.',
        completeTitle: 'Your vault is ready, {name}',
        completeFallbackName: 'driver',
        completeLead: 'Export a tiny setup file, try sample data, or head straight in.',
        enterVault: 'Enter my vault',
        exportSetup: 'Save setup to file',
      },
      why: {
        platformsSummary: 'Why we ask',
        platformsBody: 'Active platforms drive terminology, colors, and filters across the app.',
        profileSummary: 'Why we ask',
        profileBody: 'Exports and summaries read better with your name and a recognizable avatar.',
        regionSummary: 'Why we ask',
        regionBody: 'Currency and mileage rules follow your country so numbers stay trustworthy.',
        vehicleSummary: 'Why we ask',
        vehicleBody: 'Vehicle type unlocks the right cost fields when we estimate per-shift expenses.',
        secondVehicleSummary: 'Why we ask',
        secondVehicleBody: 'Many drivers switch vehicles by day; two profiles keep mileage honest.',
        homeBaseSummary: 'Why we ask',
        homeBaseBody: 'Zone tags help you spot which areas pay best over time.',
        scheduleSummary: 'Why we ask',
        scheduleBody: 'We schedule gentle reminders around the times you actually drive.',
        weeklyGoalSummary: 'Why we ask',
        weeklyGoalBody: 'A visible target keeps earnings momentum without judgment.',
        longTermGoalsSummary: 'Why we ask',
        longTermGoalsBody: 'Longer horizons smooth out slow weeks and busy seasons.',
        taxSummary: 'Why we ask',
        taxBody: 'This is guidance only — not tax advice. It powers set-aside reminders.',
        hstSummary: 'Why we ask',
        hstBody: 'Registered collectors have different worksheets than drivers who only earn T4-style income.',
        distanceSummary: 'Why we ask',
        distanceBody: 'Platforms mix km and miles; we store one consistent unit for you.',
        themeSummary: 'Why we ask',
        themeBody: 'Comfortable contrast matters when you log shifts at night.',
        notifySummary: 'Why we ask',
        notifyBody: 'You stay in control — everything runs locally in this browser.',
      },
      notify: {
        shiftReminders: 'Shift reminders',
        goalAlerts: 'Goal progress nudges',
        taxReminders: 'Tax deadline reminders',
        weeklyDigest: 'Weekly summary email (local draft only)',
      },
      validation: {
        platforms: 'Pick at least one platform.',
        name: 'Please enter your name.',
        country: 'Choose a country.',
        vehicle: 'Add a nickname and vehicle type.',
        secondVehicle: 'Fill in the second vehicle or turn off “add another”.',
        tax: 'Enter a withholding percentage between 0 and 80.',
      },
      sample: { load: 'Load two weeks of sample shifts', loaded: 'Sample shifts added — marked as placeholders.' },
    },
    shifts: {
      addShift: 'Add shift',
      editShift: 'Edit shift',
      deleteShift: 'Delete shift',
      duplicateShift: 'Duplicate shift',
      endShift: 'End shift',
      startShift: 'Start shift',
      shiftTimer: 'Shift timer',
      savedToast: 'Shift saved',
      deletedToast: 'Shift moved to trash',
      restoredToast: 'Shift restored',
      undo: 'Undo',
      timerStarted: 'Shift timer started',
      timerNotRunning: 'No active shift timer',
      template: 'Template',
      templates: 'Templates',
      noTemplates: 'No templates yet.',
      saveAsTemplate: 'Save as template',
      templateName: 'Template name',
      templateNamePlaceholder: 'e.g. Dinner rush',
      purgeTrash: 'Purge trash',
      purgedToast: 'Trash purged',
      bulkImport: 'Bulk import',
      importLead: 'Upload a CSV to import shifts. Preview shows the first 5 rows.',
      importPreview: 'Preview (first 5 rows)',
      importAppend: 'Append',
      importReplace: 'Replace all',
      importParseError: 'Could not parse CSV.',
      importDone: 'Imported {count} shifts.',
      notes: 'Notes',
      notesPlaceholder: 'Optional notes…',
      gross: 'Gross',
      net: 'Net',
      expenses: 'Expenses',
      duration: 'Duration',
      orders: 'Orders',
      tips: 'Tips',
      bonus: 'Bonus',
      distance: 'Distance',
      unitKm: 'km',
      unitMiles: 'miles',
      date: 'Date',
      startTime: 'Start time',
      endTime: 'End time',
      advancedToggle: 'Basic / Advanced',
      onlineMinutes: 'Online minutes',
      activeMinutes: 'Active minutes',
      vehicle: 'Vehicle',
      vehicleNone: 'No vehicle',
      vehicleEstimate: 'Vehicle estimate',
      weather: 'Weather',
      weatherClear: 'Clear',
      weatherRain: 'Rain',
      weatherSnow: 'Snow',
      weatherFog: 'Fog',
      weatherHeat: 'Heat',
      zone: 'Zone',
      zonePlaceholder: 'e.g. Downtown',
      mood: 'Mood',
      platform: 'Platform',
      emptyTitle: 'No shifts yet',
      emptyMessage: 'Log your first shift to see earnings and trends.',
      deleteConfirm: 'Delete this shift? This cannot be undone.',
    },
    analytics: {
      title: 'Analytics',
      subtitle: 'Earnings, pace, and patterns',
      hourlyRate: 'Hourly rate',
      netHourly: 'Net hourly',
      earnings: 'Earnings',
      distance: 'Distance',
      tips: 'Tips',
      orders: 'Orders',
      zones: 'Zones',
      trends: 'Trends',
      heatmap: 'Heatmap',
      scatter: 'Scatter',
      byDayOfWeek: 'By day of week',
      byHour: 'By hour of day',
      utilization: 'Utilization',
      records: 'Personal records',
      projection: 'Week projection',
      streak: 'Streak',
      compare: 'Compare periods',
      recentActivity: 'Recent activity',
      topShifts: 'Top earning shifts',
      zeroDays: 'Zero days',
      bestWindow: 'Best windows',
      bestDay: 'Best day',
      bestHour: 'Best hour',
      bestZone: 'Best zone',
      lastPeriod: 'Last week',
      thisPeriod: 'This week',
      baseIncome: 'Base',
      earningsVsHours: 'Earnings vs Hours',
      emptyTitle: 'Not enough data yet',
      emptyMessage: 'Log a few shifts to unlock charts and insights.',
    },
    notifications: {
      title: 'Notifications',
      permissionDenied: 'Notifications are blocked in this browser.',
      enableHint: 'Enable notifications to get shift reminders and nudges.',
      reminderShift: 'Shift reminder',
      goalMet: 'Goal reached',
      taxDeadline: 'Tax deadline approaching',
      weeklySummary: 'Weekly summary',
      openSettings: 'Open settings',
    },
    errors: {
      generic: 'Something went wrong. Try again.',
      offline: 'You appear to be offline.',
      network: 'Network request failed. Check your connection.',
      dbOpen: 'Could not open local database.',
      dbMigration: 'Database upgrade failed.',
      invalidInput: 'Check your entries and try again.',
      notFound: 'That item could not be found.',
      permission: 'Permission denied.',
      importFailed: 'Import failed. Check the file format.',
      exportFailed: 'Export failed. Try again.',
      viewRender: 'This screen could not be loaded.',
      storeBindMissing: 'Store bind: element not found.',
    },
    vehicles: {
      title: 'Vehicles',
      add: 'Add vehicle',
      edit: 'Edit vehicle',
      fuel: 'Fuel',
      ev: 'Electric',
      maintenance: 'Maintenance',
      mileage: 'Mileage',
      depreciation: 'Depreciation',
      efficiency: 'Efficiency',
    },
    expenses: {
      title: 'Expenses',
      add: 'Add expense',
      editTitle: 'Edit expense',
      subtitle: 'Track fuel, maintenance, and business costs',
      category: 'Category',
      categories: {
        fuel: 'Fuel',
        maintenance: 'Maintenance',
        parking: 'Parking',
        tolls: 'Tolls',
        insurance: 'Insurance',
        registration: 'Registration',
        phone: 'Phone',
        data_plan: 'Data plan',
        car_wash: 'Car wash',
        supplies: 'Supplies',
        meals: 'Meals',
        bank_fees: 'Bank fees',
        software: 'Software',
        accounting: 'Accounting',
        other: 'Other',
      },
      uncategorized: 'Uncategorized',
      amount: 'Amount',
      date: 'Date',
      platformAssignment: 'Platform',
      businessUsePct: 'Business use %',
      businessUseLabel: '{pct}% used for delivery work',
      notes: 'Notes',
      notesPlaceholder: 'Optional note…',
      receipt: 'Receipt',
      receiptHint: 'Upload a receipt photo (saved locally).',
      receiptAttached: 'Receipt attached.',
      recurring: 'Recurring',
      recurringInterval: 'Recurring interval',
      recurringWeekly: 'Weekly',
      recurringMonthly: 'Monthly',
      recurringAnnual: 'Annual',
      hstItc: 'HST / ITC amount',
      savedToast: 'Expense saved',
      deletedToast: 'Expense deleted',
      autoExpenseTitle: 'Auto fuel expense',
      autoExpenseNote: 'Auto-created from shift #{shiftId}',
      confirmAutoExpense: 'Confirm expense',
      filterStartDate: 'Start date',
      filterEndDate: 'End date',
      minAmount: 'Min amount',
      maxAmount: 'Max amount',
      receiptOnly: 'Has receipt',
      sortDateDesc: 'Date (newest)',
      sortDateAsc: 'Date (oldest)',
      sortAmountDesc: 'Amount (high to low)',
      sortAmountAsc: 'Amount (low to high)',
      sortCategory: 'Category (A-Z)',
      sortPlatform: 'Platform (A-Z)',
      emptyTitle: 'No expenses yet',
      emptyMessage: 'Track fuel, maintenance, and other gig costs here.',
    },
    platforms: {
      title: 'Platforms',
      switcher: 'Platform filter',
      add: 'Add platform',
      config: 'Platform settings',
      terminology: 'Terminology',
      settingsSectionTitle: 'Platforms',
      settingsSectionLead: 'Manage active gig apps, per-platform goals, and how the header switcher behaves.',
      switcherMode: 'Header switcher style',
      switcherTabs: 'Tabs',
      switcherDropdown: 'Dropdown',
      switcherModeSaved: 'Switcher preference saved.',
      weeklyGoal: 'Weekly goal ($)',
      monthlyGoal: 'Monthly goal ($)',
      taxRate: 'Tax rate override (%)',
      notes: 'Notes',
      helpLink: 'Help center',
      apiDisclaimer:
        'Macadam is not connected to any delivery platform API. Figures you enter stay on this device only.',
      deactivate: 'Deactivate',
      deactivateTitle: 'Deactivate platform?',
      deactivateMessage: 'Historical shifts for {name} stay in your vault. You can add this platform again later.',
      deactivated: 'Platform deactivated.',
      lastActive: 'Keep at least one active platform.',
      saved: 'Platform settings saved.',
      noInactive: 'Every catalog platform is already active.',
      pickPlatform: 'Choose a platform…',
      added: 'Platform added.',
      reactivate: 'Turn back on',
      reactivated: 'Platform reactivated.',
      inactiveHeading: 'Inactive platforms',
      cardMeta: 'Per-platform targets and notes',
      otherExplain: 'Name and color appear in the switcher and reports.',
      otherName: 'Display name',
      otherColor: 'Accent color',
      activateOtherTitle: 'Set up “Other”',
    },
    tax: {
      title: 'Tax',
      subtitle: 'Year view, set-aside, and filing helpers',
      taxYear: 'Tax year',
      virtualJar: 'Tax set-aside tracker',
      targetSetAside: 'Target set-aside',
      currentSetAside: 'Current set-aside',
      hstCollectedTracker: 'HST/GST collected',
      itcTracker: 'Input tax credits (ITC)',
      collected: 'Collected',
      remittable: 'Estimated remittable',
      incomeSnapshot: 'Income snapshot',
      grossIncome: 'Gross income',
      businessExpenses: 'Business expenses',
      netIncome: 'Net income',
      netAfterSetAside: 'Net after set-aside',
      provinceStatePresets: 'Province/state tax rate presets',
      province: 'Province',
      state: 'State',
      applyPreset: 'Apply preset to profile',
      currentRate: 'Current withholding rate',
      presetApplied: 'Tax rate updated to {rate}.',
      mileageDeduction: 'Mileage and cost comparison',
      totalDistance: 'Business distance',
      standardMileage: 'Standard mileage method',
      actualCost: 'Actual cost method',
      recommendedMethod: 'Higher deduction this year',
      methodActual: 'Actual cost',
      methodStandard: 'Standard mileage',
      kilometres: 'km',
      miles: 'mi',
      cppEstimator: 'CPP estimator (Canada)',
      seTaxEstimator: 'Self-employment tax estimator (US)',
      estimatedValue: 'Estimated annual amount',
      cppNote: 'Planning estimate only; verify with CRA worksheets.',
      seTaxNote: 'Planning estimate only; verify with IRS worksheets.',
      installmentDeadlines: 'Installment deadlines',
      overdue: 'overdue',
      t2125: {
        title: 'T2125 helper (Canada)',
        grossIncome: 'Part 3A — Gross business income',
        advertising: 'Line 8521 — Advertising',
        meals: 'Line 8523 — Meals and entertainment',
        motorVehicle: 'Line 9281 — Motor vehicle expenses',
        supplies: 'Line 8811 — Office expenses and supplies',
        other: 'Part 4 — Other deductible expenses',
        netIncome: 'Part 5 — Net business income',
      },
      scheduleC: {
        title: 'Schedule C helper (US)',
        partIIncome: 'Part I — Income',
        partIIExpenses: 'Part II — Expenses',
        carTruck: 'Line 9 — Car and truck expenses',
        depreciation: 'Line 13 — Depreciation',
        homeOffice: 'Line 30 — Home office deduction',
        other: 'Part V — Other expenses',
        netProfit: 'Line 31 — Net profit or loss',
      },
      referenceLinks: 'Official references',
      links: {
        businessIncomeGuide: 'Business income and expenses',
        scheduleCGuide: 'Schedule C guide',
        hstGuide: 'GST/HST for businesses',
        estimatedTaxes: 'Estimated taxes',
      },
      footnoteCanada: 'Not tax advice. Verify your filing with CRA guidance or a tax professional.',
      footnoteUs: 'Not tax advice. Verify your filing with IRS guidance or a tax professional.',
      exportSummary: 'Export tax summary',
      exportHint: 'Download this year summary as JSON or CSV.',
      exportJson: 'Export JSON',
      exportCsv: 'Export CSV',
      exportedJson: 'Tax summary JSON exported.',
      exportedCsv: 'Tax summary CSV exported.',
    },
    goals: {
      title: 'Goals',
      weeklyTarget: 'Weekly target',
      badges: 'Badges',
      xp: 'XP',
      challenges: 'Challenges',
      streakDays: 'Day streak',
      level: 'Level',
      weeksHit: 'Weeks hit',
      of: 'of',
      thermometer: 'Thermometer',
      activeGoals: 'Active goals',
      history: 'Goal history',
      to: 'to',
      hit: 'hit',
      inProgress: 'in progress',
    },
    settings: {
      title: 'Settings',
      subtitle: 'Locale, display, and data',
      language: 'Language',
      dateFormat: 'Date format',
      timeFormat: 'Time format',
      theme: 'Theme',
      distanceUnit: 'Distance unit',
      currency: 'Currency',
      notifications: 'Notifications',
      dataExport: 'Export data',
      dangerZone: 'Danger zone',
      about: 'About',
    },
    pwa: {
      sectionTitle: 'Device features',
      sectionLead: 'Enable optional browser APIs that improve the on-device experience. Permissions are only requested when you explicitly toggle them.',
      capabilityHeading: 'Capabilities detected',
      supported: 'Supported',
      unsupported: 'Not available in this browser',
      requestNotifications: 'Enable notifications',
      notificationsGranted: 'Notifications enabled',
      notificationsDenied: 'Notifications blocked by browser',
      notificationsUnsupported: 'Notifications are not available here',
      testVibrate: 'Test vibration',
      vibrationOk: 'Sent a quick haptic pulse.',
      vibrationUnsupported: 'This device cannot vibrate.',
      toggleFullscreen: 'Toggle fullscreen',
      fullscreenOn: 'Entered fullscreen.',
      fullscreenOff: 'Exited fullscreen.',
      fullscreenUnsupported: 'Fullscreen is not available here.',
      backgroundSync: 'Background Sync',
      backgroundSyncOn: 'Deferred exports will retry automatically.',
      backgroundSyncOff: 'Background Sync unavailable — exports retry on next open.',
      wakeLock: 'Screen Wake Lock',
      wakeLockOn: 'Screen stays awake during active shift timers.',
      wakeLockOff: 'Wake Lock not available in this browser.',
      fileSystem: 'File System Access',
      fileSystemOn: 'Choose where to save reports and backups.',
      fileSystemOff: 'Falls back to download folder.',
      shareTarget: 'Share Target',
      shareTargetOn: 'Other apps can share text into Macadam.',
      shareTargetOff: 'Share Target registers when installed as a PWA.',
      shareIntentTitle: 'Shared content received',
      shareIntentBody: '{title} {text}',
    },
    zones: {
      sectionTitle: 'Zone management',
      sectionLead: 'Rename, merge, or remove zone tags across every shift in your vault.',
      emptyTitle: 'No zones tagged yet',
      emptyMessage: 'Add a zone label on a shift to start tracking by area.',
      tableHeader: {
        zone: 'Zone',
        shifts: 'Shifts',
        gross: 'Gross',
        hourly: 'Hourly',
        perKm: 'Per km',
        expenses: 'Allocated expenses',
        actions: 'Actions',
      },
      rename: 'Rename',
      renameTitle: 'Rename zone',
      renameLabel: 'New name',
      mergeTitle: 'Merge zones',
      mergeInto: 'Merge into',
      mergeAction: 'Merge selected',
      mergeHelp: 'Select two or more rows to merge into a single zone tag.',
      delete: 'Clear tag',
      deleteConfirmTitle: 'Clear zone tag?',
      deleteConfirmMessage: 'Shifts will keep their data; only the {zone} tag is removed.',
      renamedToast: 'Renamed {count} shifts.',
      mergedToast: 'Merged {count} shifts.',
      clearedToast: 'Cleared tag from {count} shifts.',
      unallocated: 'Unallocated (no shift that day)',
    },
    reports: {
      title: 'Reports',
      export: 'Export',
      csv: 'CSV',
      json: 'JSON',
      print: 'Print view',
      yearInReview: 'Year in review',
    },
    schedule: {
      title: 'Schedule',
      subtitle: 'Planning and calendar',
      weekView: 'Week',
      monthView: 'Month',
      timeBlock: 'Time block',
      planningMode: 'Planning mode',
    },
    search: {
      title: 'Search',
      placeholder: 'Search shifts and expenses',
      filter: 'Filters',
      noResults: 'No matches',
    },
    modules: {
      onboarding: {
        title: 'Onboarding module',
        body: 'Orchestrator copy ships with Phase 2 (`modules/onboarding/`).',
      },
      platforms: {
        title: 'Platforms module',
        body: 'Switcher and per-platform config ship with Phase 2 (`modules/platforms/`).',
      },
      shifts: {
        title: 'Shifts module',
        body: 'CRUD, timer, and forms ship with Phase 2 (`modules/shifts/`).',
      },
      expenses: {
        title: 'Expenses module',
        body: 'Categories and recurring rules ship with Phase 2 (`modules/expenses/`).',
      },
      analytics: {
        title: 'Analytics module',
        body: 'Aggregations and chart views ship with Phase 2 (`modules/analytics/`).',
      },
      tax: {
        title: 'Tax module',
        body: 'Regional worksheets ship with Phase 2 (`modules/tax/`).',
      },
      vehicles: {
        title: 'Vehicles module',
        body: 'Garage and cost models ship with Phase 2 (`modules/vehicles/`).',
      },
      goals: {
        title: 'Goals module',
        body: 'Badges, XP, and streaks ship with Phase 2 (`modules/goals/`).',
      },
      reports: {
        title: 'Reports module',
        body: 'CSV/JSON/print/QR exports ship with Phase 2 (`modules/reports/`).',
      },
      search: {
        title: 'Search module',
        body: 'Fuse.js integration ships with Phase 2 (`modules/search/`).',
      },
      notifications: {
        title: 'Notifications module',
        body: 'All notification types ship with Phase 2 (`modules/notifications/`).',
      },
      schedule: {
        title: 'Schedule module',
        body: 'Calendar and planning ship with Phase 2 (`modules/schedule/`).',
      },
      settings: {
        title: 'Settings module',
        body: 'Full preferences UI ships with Phase 2 (`modules/settings/`).',
      },
    },
    views: {
      dashboard: {
        title: 'Dashboard',
        greeting: 'Here is your snapshot',
        placeholderBody: 'Dashboard widgets and copy finalize in Phase 2 (`views/dashboard.js`).',
      },
      shifts: {
        title: 'Shifts',
        subtitle: 'Log shifts, start timers, and import history',
        placeholderBody: 'Shift list and filters finalize in Phase 2 (`views/shifts-view.js`).',
      },
      analytics: {
        title: 'Analytics',
        placeholderBody: 'Route-level analytics layout finalizes in Phase 2 (`views/analytics-view.js`).',
      },
      tax: {
        title: 'Tax',
        placeholderBody: 'Tax view copy finalizes in Phase 2 (`views/tax-view.js`).',
      },
      vehicles: {
        title: 'Vehicles',
        placeholderBody: 'Vehicles view copy finalizes in Phase 2 (`views/vehicles-view.js`).',
      },
      schedule: {
        title: 'Schedule',
        placeholderBody: 'Schedule view copy finalizes in Phase 2 (`views/schedule-view.js`).',
      },
      goals: {
        title: 'Goals',
        placeholderBody: 'Goals view copy finalizes in Phase 2 (`views/goals-view.js`).',
      },
      reports: {
        title: 'Reports',
        placeholderBody: 'Reports view copy finalizes in Phase 2 (`views/reports-view.js`).',
      },
      settings: {
        title: 'Settings',
        placeholderBody: 'Settings view copy finalizes in Phase 2 (`views/settings-view.js`).',
      },
      onboarding: {
        title: 'Onboarding',
        placeholderBody: 'Onboarding view shell finalizes in Phase 2 (`views/onboarding-view.js`).',
      },
      about: {
        title: 'About Macadam',
        placeholderBody:
          'Data stays on your device. Full portability story and export links finalize in Phase 2.',
      },
      print: {
        title: 'Print',
        placeholderBody: 'Print-friendly earnings layouts ship with Phase 2 (`modules/reports/`).',
      },
      search: {
        title: 'Search',
        placeholderBody: 'Fuzzy search across shifts and expenses ships in Phase 2 (`modules/search/`).',
      },
    },
    ui: {
      modal: {
        close: 'Close',
      },
      confirm: {
        title: 'Are you sure?',
        destructive: 'This action is hard to undo.',
        typeToConfirm: 'Type {value} to confirm',
      },
      toast: {
        success: 'Saved',
        error: 'Error',
        warning: 'Warning',
        info: 'Info',
        celebration: 'Celebration',
        dismiss: 'Dismiss',
      },
      fab: {
        addShift: 'Quick add shift',
        endShift: 'End shift',
      },
      drawer: {
        close: 'Close',
      },
      progressRing: {
        label: 'Progress',
      },
      skeleton: {
        loading: 'Loading',
      },
      emptyState: {
        defaultTitle: 'Nothing here yet',
        defaultMessage: 'Try adding an item or changing filters.',
      },
      keypad: {
        title: 'Enter amount',
        confirm: 'Done',
        clear: 'Clear',
        backspace: 'Backspace',
        open: 'Keypad',
      },
    },
  },
  fr: {
    app: {
      name: 'Macadam',
      tagline: 'Gains de gig, local d’abord',
      updateAvailable: 'Mise à jour disponible — rechargez pour la dernière version',
      reload: 'Recharger',
      offlineBanner: 'Vous êtes hors ligne. Les changements se synchronisent à la reconnexion.',
      online: 'En ligne',
      offline: 'Hors ligne',
      navDashboard: 'Tableau de bord',
      navShifts: 'Quarts',
      navAnalytics: 'Analytique',
      navGoals: 'Objectifs',
      navSettings: 'Paramètres',
      navTax: 'Impôts',
      navVehicles: 'Véhicules',
      navSchedule: 'Horaire',
      navReports: 'Rapports',
      navSearch: 'Recherche',
      navMore: 'Plus',
      platformAll: 'Tout',
      headerAria: 'En-tête de l’app',
      navAria: 'Navigation principale',
      skipToContent: 'Passer au contenu principal',
    },
    common: {
      save: 'Enregistrer',
      cancel: 'Annuler',
      close: 'Fermer',
      confirm: 'Confirmer',
      all: 'Tout',
      sort: 'Trier',
      delete: 'Supprimer',
      edit: 'Modifier',
      done: 'Terminé',
      back: 'Retour',
      next: 'Suivant',
      loading: 'Chargement…',
      optional: 'Facultatif',
      required: 'Obligatoire',
      yes: 'Oui',
      no: 'Non',
      copy: 'Copier',
      share: 'Partager',
      retry: 'Réessayer',
    },
    onboarding: {
      title: 'Bienvenue sur Macadam',
      subtitle: 'Suivez vos gains dans une seule app',
      continue: 'Continuer',
      skip: 'Passer pour l’instant',
      finish: 'Commencer',
      stepProgress: 'Étape {current} sur {total}',
      welcomeTitle: 'Bienvenue',
      platformsTitle: 'Vos plateformes',
      vehicleTitle: 'Votre véhicule',
      goalsTitle: 'Objectif hebdomadaire',
      notificationsTitle: 'Restez sur la bonne voie',
      privacyTitle: 'Confidentialité',
      summaryTitle: 'Tout est prêt',
      placeholderBody:
        'Le texte détaillé de l’accueil arrive en phase 2 (orchestrateur + steps.js). Les clés restent stables pour `t()`.',
      tryDemo: 'Essayer la démo',
      demoEnabled: 'Mode démo activé.',
      resumeTitle: 'Poursuivre la configuration ?',
      resumeMessage: 'Une configuration est déjà en cours pour cette session. Reprendre ou recommencer.',
      resumeContinue: 'Continuer',
      resumeStartOver: 'Recommencer',
      completeToast: 'Votre coffre est prêt. Bienvenue !',
      exportDone: 'Fichier de configuration téléchargé.',
      resetNeedExport: 'Exportez une sauvegarde avant de réinitialiser le coffre.',
      resetTitle: 'Réinitialiser le coffre',
      resetMessage: 'Cela supprime toutes les données Macadam locales sur cet appareil.',
      resetConfirm: 'Tout effacer',
      motivation: {
        high: 'Objectif ambitieux — on vous encourage chaque semaine.',
        mid: 'Bon équilibre entre défi et réalisme.',
        low: 'Progression douce — vous pourrez augmenter l’objectif plus tard.',
        start: 'Chaque parcours commence par un quart enregistré.',
      },
      schedule: {
        flexible: 'Horaire flexible',
        weekdays: 'Surtout en semaine',
        evenings: 'Soirées',
        weekends: 'Week-ends',
      },
      theme: { light: 'Clair', dark: 'Sombre', auto: 'Auto' },
      vehicleTypes: {
        gas: 'Essence',
        hybrid: 'Hybride',
        ev: 'Électrique',
        motorcycle: 'Moto',
        bicycle: 'Vélo',
        ebike: 'Vélo électrique',
        scooter: 'Trottinette',
        walking: 'À pied',
      },
      steps: {
        platformsTitle: 'Où conduit-on ?',
        platformsLead: 'Choisissez chaque plateforme utilisée. Modifiable plus tard.',
        profileTitle: 'Comment vous saluer ?',
        profileLead: 'Ce nom apparaît sur le tableau de bord et les exports.',
        driverName: 'Votre nom',
        avatarPick: 'Avatar',
        avatarInitials: 'Initiales',
        avatarCustom: 'Téléverser une photo',
        avatarUpload: 'Choisir une image',
        regionTitle: 'Pays ou région',
        regionLead: 'Devise, distance et repères fiscaux en découlent.',
        country: 'Pays',
        countryCA: 'Canada',
        countryUS: 'États-Unis',
        countryUK: 'Royaume-Uni',
        currencyHint: 'Devise',
        vehicleTitle: 'Véhicule principal',
        vehicleLead: 'Le type aide à estimer les coûts plus tard.',
        vehicleNickname: 'Surnom',
        vehicleType: 'Type de véhicule',
        make: 'Marque',
        model: 'Modèle',
        year: 'Année',
        secondVehicleTitle: 'Un deuxième véhicule ?',
        secondVehicleLead: 'Facultatif — utile si vous alternez auto et vélo.',
        addAnotherVehicle: 'Ajouter un deuxième véhicule',
        homeBaseTitle: 'Zone de départ',
        homeBaseLead: 'Court libellé pour la zone où vous commencez souvent.',
        homeBaseLabel: 'Libellé de zone',
        homeBasePlaceholder: 'ex. Centre-ville',
        scheduleTitle: 'Horaire typique',
        scheduleLead: 'Aide pour les rappels et la planification.',
        weeklyGoalTitle: 'Objectif hebdomadaire (brut)',
        weeklyGoalLead: 'Utilisé pour l’anneau d’objectif et les rappels.',
        weeklyGoalLabel: 'Cible hebdomadaire (brut)',
        longTermGoalsTitle: 'Objectifs mensuel et annuel',
        longTermGoalsLead: 'Préremplis à partir de l’hebdomadaire — ajustez librement.',
        monthlyGoal: 'Cible mensuelle',
        annualGoal: 'Cible annuelle',
        taxTitle: 'Mise de côté fiscale',
        taxLead: 'Pourcentage approximatif à mettre de côté sur le brut.',
        province: 'Province ou territoire',
        state: 'État',
        taxRegionPlaceholder: 'Choisir…',
        taxWithholding: 'Pourcentage de retenue',
        applyPreset: 'Appliquer le préréglage régional',
        hstTitle: 'TPS / TVH',
        hstLead: 'Canada seulement — pour les feuilles TPS/TVH.',
        hstToggle: 'Je perçois ou remets la TPS / TVH',
        hstSkip: 'La TPS / TVH ne s’applique pas au pays choisi.',
        distanceTitle: 'Unités de distance',
        distanceLead: 'Affichées sur les quarts et le kilométrage.',
        unitKm: 'Kilomètres',
        unitMi: 'Miles',
        themeTitle: 'Apparence',
        themeLead: 'Modifiable à tout moment dans Paramètres.',
        notifyTitle: 'Notifications',
        notifyLead: 'Tout reste local — rien n’est téléversé.',
        completeTitle: 'Votre coffre est prêt, {name}',
        completeFallbackName: 'conducteur',
        completeLead: 'Exportez une petite configuration, chargez des exemples ou entrez directement.',
        enterVault: 'Entrer dans mon coffre',
        exportSetup: 'Enregistrer la configuration',
      },
      why: {
        platformsSummary: 'Pourquoi on demande',
        platformsBody: 'Les plateformes actives pilotent terminologie, couleurs et filtres.',
        profileSummary: 'Pourquoi on demande',
        profileBody: 'Les exports sont plus clairs avec votre nom et un avatar.',
        regionSummary: 'Pourquoi on demande',
        regionBody: 'La devise et les règles de distance suivent votre pays.',
        vehicleSummary: 'Pourquoi on demande',
        vehicleBody: 'Le type de véhicule débloque les bons champs de coût.',
        secondVehicleSummary: 'Pourquoi on demande',
        secondVehicleBody: 'Deux profils gardent le kilométrage honnête si vous alternez.',
        homeBaseSummary: 'Pourquoi on demande',
        homeBaseBody: 'Les zones aident à repérer où vous gagnez le plus.',
        scheduleSummary: 'Pourquoi on demande',
        scheduleBody: 'Les rappels s’alignent sur vos plages habituelles.',
        weeklyGoalSummary: 'Pourquoi on demande',
        weeklyGoalBody: 'Une cible visible sans jugement.',
        longTermGoalsSummary: 'Pourquoi on demande',
        longTermGoalsBody: 'Les horizons lissent les semaines lentes ou chargées.',
        taxSummary: 'Pourquoi on demande',
        taxBody: 'Indicatif seulement — pas un conseil fiscal.',
        hstSummary: 'Pourquoi on demande',
        hstBody: 'Les obligations TPS/TVH diffèrent selon l’enregistrement.',
        distanceSummary: 'Pourquoi on demande',
        distanceBody: 'Une unité cohérente pour tous les quarts.',
        themeSummary: 'Pourquoi on demande',
        themeBody: 'Un bon contraste pour saisir la nuit.',
        notifySummary: 'Pourquoi on demande',
        notifyBody: 'Vous gardez le contrôle — tout tourne localement.',
      },
      notify: {
        shiftReminders: 'Rappels de quart',
        goalAlerts: 'Nudges d’objectif',
        taxReminders: 'Rappels d’échéances fiscales',
        weeklyDigest: 'Résumé hebdomadaire (brouillon local)',
      },
      validation: {
        platforms: 'Choisissez au moins une plateforme.',
        name: 'Entrez votre nom.',
        country: 'Choisissez un pays.',
        vehicle: 'Ajoutez un surnom et un type de véhicule.',
        secondVehicle: 'Remplissez le 2e véhicule ou décochez l’option.',
        tax: 'Indiquez un pourcentage entre 0 et 80.',
      },
      sample: { load: 'Charger deux semaines d’exemple', loaded: 'Quarts d’exemple ajoutés (marqueurs).' },
    },
    shifts: {
      addShift: 'Ajouter un quart',
      editShift: 'Modifier le quart',
      deleteShift: 'Supprimer le quart',
      duplicateShift: 'Dupliquer le quart',
      endShift: 'Terminer le quart',
      startShift: 'Commencer le quart',
      shiftTimer: 'Chronomètre de quart',
      savedToast: 'Quart enregistré',
      deletedToast: 'Quart déplacé à la corbeille',
      restoredToast: 'Quart restauré',
      undo: 'Annuler',
      timerStarted: 'Chronomètre démarré',
      timerNotRunning: 'Aucun chronomètre en cours',
      template: 'Modèle',
      templates: 'Modèles',
      noTemplates: 'Aucun modèle pour le moment.',
      saveAsTemplate: 'Enregistrer comme modèle',
      templateName: 'Nom du modèle',
      templateNamePlaceholder: 'ex. Rush du soir',
      purgeTrash: 'Vider la corbeille',
      purgedToast: 'Corbeille vidée',
      bulkImport: 'Import groupé',
      importLead: 'Téléversez un CSV pour importer des quarts. L’aperçu montre les 5 premières lignes.',
      importPreview: 'Aperçu (5 premières lignes)',
      importAppend: 'Ajouter',
      importReplace: 'Tout remplacer',
      importParseError: 'Impossible de lire le CSV.',
      importDone: '{count} quarts importés.',
      notes: 'Notes',
      notesPlaceholder: 'Notes facultatives…',
      gross: 'Brut',
      net: 'Net',
      expenses: 'Dépenses',
      duration: 'Durée',
      orders: 'Commandes',
      tips: 'Pourboires',
      bonus: 'Prime',
      distance: 'Distance',
      unitKm: 'km',
      unitMiles: 'milles',
      date: 'Date',
      startTime: 'Heure de début',
      endTime: 'Heure de fin',
      advancedToggle: 'Basique / Avancé',
      onlineMinutes: 'Minutes en ligne',
      activeMinutes: 'Minutes actives',
      vehicle: 'Véhicule',
      vehicleNone: 'Aucun véhicule',
      vehicleEstimate: 'Estimation véhicule',
      weather: 'Météo',
      weatherClear: 'Clair',
      weatherRain: 'Pluie',
      weatherSnow: 'Neige',
      weatherFog: 'Brouillard',
      weatherHeat: 'Chaleur',
      zone: 'Zone',
      zonePlaceholder: 'ex. Centre-ville',
      mood: 'Humeur',
      platform: 'Plateforme',
      emptyTitle: 'Aucun quart',
      emptyMessage: 'Enregistrez votre premier quart pour voir les tendances.',
      deleteConfirm: 'Supprimer ce quart ? Cette action est irréversible.',
    },
    analytics: {
      title: 'Analytique',
      subtitle: 'Gains, rythme et habitudes',
      hourlyRate: 'Taux horaire',
      netHourly: 'Taux horaire net',
      earnings: 'Gains',
      distance: 'Distance',
      tips: 'Pourboires',
      orders: 'Commandes',
      zones: 'Zones',
      trends: 'Tendances',
      heatmap: 'Carte de chaleur',
      scatter: 'Nuage de points',
      byDayOfWeek: 'Par jour de la semaine',
      byHour: 'Par heure',
      utilization: 'Utilisation',
      records: 'Records personnels',
      projection: 'Projection hebdomadaire',
      streak: 'Série',
      compare: 'Comparer les périodes',
      recentActivity: 'Activité récente',
      topShifts: 'Meilleurs quarts',
      zeroDays: 'Jours sans quart',
      bestWindow: 'Meilleures plages',
      bestDay: 'Meilleur jour',
      bestHour: 'Meilleure heure',
      bestZone: 'Meilleure zone',
      lastPeriod: 'Semaine précédente',
      thisPeriod: 'Cette semaine',
      baseIncome: 'Base',
      earningsVsHours: 'Gains vs heures',
      emptyTitle: 'Pas assez de données',
      emptyMessage: 'Ajoutez quelques quarts pour débloquer graphiques et analyses.',
    },
    notifications: {
      title: 'Notifications',
      permissionDenied: 'Les notifications sont bloquées dans ce navigateur.',
      enableHint: 'Activez les notifications pour les rappels de quart.',
      reminderShift: 'Rappel de quart',
      goalMet: 'Objectif atteint',
      taxDeadline: 'Échéance fiscale proche',
      weeklySummary: 'Résumé hebdomadaire',
      openSettings: 'Ouvrir les paramètres',
    },
    errors: {
      generic: 'Une erreur s’est produite. Réessayez.',
      offline: 'Vous semblez hors ligne.',
      network: 'La requête réseau a échoué. Vérifiez la connexion.',
      dbOpen: 'Impossible d’ouvrir la base locale.',
      dbMigration: 'La mise à niveau de la base a échoué.',
      invalidInput: 'Vérifiez les champs et réessayez.',
      notFound: 'Élément introuvable.',
      permission: 'Permission refusée.',
      importFailed: 'Import impossible. Vérifiez le format du fichier.',
      exportFailed: 'Export impossible. Réessayez.',
      viewRender: 'Cet écran n’a pas pu être chargé.',
      storeBindMissing: 'Liaison d’état : élément introuvable.',
    },
    vehicles: {
      title: 'Véhicules',
      add: 'Ajouter un véhicule',
      edit: 'Modifier le véhicule',
      fuel: 'Carburant',
      ev: 'Électrique',
      maintenance: 'Entretien',
      mileage: 'Kilométrage',
      depreciation: 'Amortissement',
      efficiency: 'Rendement',
    },
    expenses: {
      title: 'Dépenses',
      add: 'Ajouter une dépense',
      editTitle: 'Modifier la dépense',
      subtitle: 'Suivez carburant, entretien et coûts professionnels',
      category: 'Catégorie',
      categories: {
        fuel: 'Carburant',
        maintenance: 'Entretien',
        parking: 'Stationnement',
        tolls: 'Péages',
        insurance: 'Assurance',
        registration: 'Immatriculation',
        phone: 'Téléphone',
        data_plan: 'Forfait données',
        car_wash: 'Lavage auto',
        supplies: 'Fournitures',
        meals: 'Repas',
        bank_fees: 'Frais bancaires',
        software: 'Logiciels',
        accounting: 'Comptabilité',
        other: 'Autre',
      },
      uncategorized: 'Sans catégorie',
      amount: 'Montant',
      date: 'Date',
      platformAssignment: 'Plateforme',
      businessUsePct: 'Usage professionnel %',
      businessUseLabel: '{pct}% utilisé pour les livraisons',
      notes: 'Notes',
      notesPlaceholder: 'Note facultative…',
      receipt: 'Reçu',
      receiptHint: 'Téléversez une photo de reçu (stockée localement).',
      receiptAttached: 'Reçu joint.',
      recurring: 'Récurrent',
      recurringInterval: 'Fréquence',
      recurringWeekly: 'Hebdomadaire',
      recurringMonthly: 'Mensuel',
      recurringAnnual: 'Annuel',
      hstItc: 'Montant TPS/TVH / CTI',
      savedToast: 'Dépense enregistrée',
      deletedToast: 'Dépense supprimée',
      autoExpenseTitle: 'Dépense carburant automatique',
      autoExpenseNote: 'Créée automatiquement depuis le quart no {shiftId}',
      confirmAutoExpense: 'Confirmer la dépense',
      filterStartDate: 'Date de début',
      filterEndDate: 'Date de fin',
      minAmount: 'Montant min',
      maxAmount: 'Montant max',
      receiptOnly: 'Avec reçu',
      sortDateDesc: 'Date (récentes)',
      sortDateAsc: 'Date (anciennes)',
      sortAmountDesc: 'Montant (décroissant)',
      sortAmountAsc: 'Montant (croissant)',
      sortCategory: 'Catégorie (A-Z)',
      sortPlatform: 'Plateforme (A-Z)',
      emptyTitle: 'Aucune dépense',
      emptyMessage: 'Suivez carburant, entretien et autres coûts ici.',
    },
    platforms: {
      title: 'Plateformes',
      switcher: 'Filtre plateforme',
      add: 'Ajouter une plateforme',
      config: 'Paramètres de plateforme',
      terminology: 'Terminologie',
      settingsSectionTitle: 'Plateformes',
      settingsSectionLead: 'Gérez les apps actives, les objectifs par plateforme et le sélecteur d’en-tête.',
      switcherMode: 'Style du sélecteur (en-tête)',
      switcherTabs: 'Onglets',
      switcherDropdown: 'Menu déroulant',
      switcherModeSaved: 'Préférence du sélecteur enregistrée.',
      weeklyGoal: 'Objectif hebdomadaire ($)',
      monthlyGoal: 'Objectif mensuel ($)',
      taxRate: 'Taux fiscal local (%)',
      notes: 'Notes',
      helpLink: 'Centre d’aide',
      apiDisclaimer:
        'Macadam n’est relié à aucune API de plateforme. Les données saisies restent sur cet appareil.',
      deactivate: 'Désactiver',
      deactivateTitle: 'Désactiver la plateforme ?',
      deactivateMessage: 'Les quarts passés pour {name} restent dans le coffre. Vous pourrez réactiver plus tard.',
      deactivated: 'Plateforme désactivée.',
      lastActive: 'Gardez au moins une plateforme active.',
      saved: 'Paramètres enregistrés.',
      noInactive: 'Toutes les plateformes du catalogue sont déjà actives.',
      pickPlatform: 'Choisir une plateforme…',
      added: 'Plateforme ajoutée.',
      reactivate: 'Réactiver',
      reactivated: 'Plateforme réactivée.',
      inactiveHeading: 'Plateformes inactives',
      cardMeta: 'Cibles et notes par plateforme',
      otherExplain: 'Le nom et la couleur apparaissent dans le sélecteur et les rapports.',
      otherName: 'Nom affiché',
      otherColor: 'Couleur d’accent',
      activateOtherTitle: 'Configurer « Autre »',
    },
    tax: {
      title: 'Impôts',
      subtitle: 'Vue annuelle, mise de côté et aide à la déclaration',
      taxYear: 'Année fiscale',
      virtualJar: 'Suivi de mise de côté fiscale',
      targetSetAside: 'Mise de côté cible',
      currentSetAside: 'Mise de côté actuelle',
      hstCollectedTracker: 'TPS/TVH perçue',
      itcTracker: 'Crédits de taxe sur les intrants (CTI)',
      collected: 'Perçue',
      remittable: 'Montant estimé à remettre',
      incomeSnapshot: 'Aperçu du revenu',
      grossIncome: 'Revenu brut',
      businessExpenses: 'Dépenses d’entreprise',
      netIncome: 'Revenu net',
      netAfterSetAside: 'Net après mise de côté',
      provinceStatePresets: 'Préréglages de taux province/état',
      province: 'Province',
      state: 'État',
      applyPreset: 'Appliquer au profil',
      currentRate: 'Taux de retenue actuel',
      presetApplied: 'Taux fiscal mis à jour à {rate}.',
      mileageDeduction: 'Kilométrage et comparaison des coûts',
      totalDistance: 'Distance professionnelle',
      standardMileage: 'Méthode kilométrage standard',
      actualCost: 'Méthode des coûts réels',
      recommendedMethod: 'Déduction la plus élevée cette année',
      methodActual: 'Coûts réels',
      methodStandard: 'Kilométrage standard',
      kilometres: 'km',
      miles: 'mi',
      cppEstimator: 'Estimateur RPC (Canada)',
      seTaxEstimator: 'Estimateur travail autonome (É.-U.)',
      estimatedValue: 'Montant annuel estimé',
      cppNote: 'Estimation de planification seulement; validez avec les feuilles ARC.',
      seTaxNote: 'Estimation de planification seulement; validez avec les feuilles IRS.',
      installmentDeadlines: 'Échéances des acomptes',
      overdue: 'en retard',
      t2125: {
        title: 'Aide T2125 (Canada)',
        grossIncome: 'Partie 3A — Revenu brut d’entreprise',
        advertising: 'Ligne 8521 — Publicité',
        meals: 'Ligne 8523 — Repas et divertissement',
        motorVehicle: 'Ligne 9281 — Dépenses véhicule',
        supplies: 'Ligne 8811 — Fournitures et bureau',
        other: 'Partie 4 — Autres dépenses déductibles',
        netIncome: 'Partie 5 — Revenu net d’entreprise',
      },
      scheduleC: {
        title: 'Aide Schedule C (É.-U.)',
        partIIncome: 'Partie I — Revenu',
        partIIExpenses: 'Partie II — Dépenses',
        carTruck: 'Ligne 9 — Dépenses auto/camion',
        depreciation: 'Ligne 13 — Amortissement',
        homeOffice: 'Ligne 30 — Bureau à domicile',
        other: 'Partie V — Autres dépenses',
        netProfit: 'Ligne 31 — Profit ou perte net',
      },
      referenceLinks: 'Références officielles',
      links: {
        businessIncomeGuide: 'Revenus et dépenses d’entreprise',
        scheduleCGuide: 'Guide Schedule C',
        hstGuide: 'TPS/TVH pour entreprises',
        estimatedTaxes: 'Impôts estimés',
      },
      footnoteCanada: 'Ceci n’est pas un conseil fiscal. Vérifiez avec l’ARC ou un professionnel.',
      footnoteUs: 'Ceci n’est pas un conseil fiscal. Vérifiez avec l’IRS ou un professionnel.',
      exportSummary: 'Exporter le résumé fiscal',
      exportHint: 'Téléchargez le résumé annuel en JSON ou CSV.',
      exportJson: 'Exporter JSON',
      exportCsv: 'Exporter CSV',
      exportedJson: 'Résumé fiscal JSON exporté.',
      exportedCsv: 'Résumé fiscal CSV exporté.',
    },
    goals: {
      title: 'Objectifs',
      weeklyTarget: 'Objectif hebdomadaire',
      badges: 'Badges',
      xp: 'XP',
      challenges: 'Défis',
      streakDays: 'Série de jours',
      level: 'Niveau',
      weeksHit: 'Semaines atteintes',
      of: 'sur',
      thermometer: 'Thermomètre',
      activeGoals: 'Objectifs actifs',
      history: 'Historique des objectifs',
      to: 'à',
      hit: 'atteint',
      inProgress: 'en cours',
    },
    settings: {
      title: 'Paramètres',
      subtitle: 'Locale, affichage et données',
      language: 'Langue',
      dateFormat: 'Format de date',
      timeFormat: 'Format d’heure',
      theme: 'Thème',
      distanceUnit: 'Unité de distance',
      currency: 'Devise',
      notifications: 'Notifications',
      dataExport: 'Exporter les données',
      dangerZone: 'Zone sensible',
      about: 'À propos',
    },
    pwa: {
      sectionTitle: 'Fonctions de l’appareil',
      sectionLead: 'Activez des API de navigateur optionnelles. Les permissions ne sont demandées qu’à votre demande explicite.',
      capabilityHeading: 'Capacités détectées',
      supported: 'Pris en charge',
      unsupported: 'Non disponible sur ce navigateur',
      requestNotifications: 'Activer les notifications',
      notificationsGranted: 'Notifications activées',
      notificationsDenied: 'Notifications bloquées par le navigateur',
      notificationsUnsupported: 'Notifications indisponibles ici',
      testVibrate: 'Tester la vibration',
      vibrationOk: 'Une vibration rapide a été envoyée.',
      vibrationUnsupported: 'Cet appareil ne peut pas vibrer.',
      toggleFullscreen: 'Basculer le plein écran',
      fullscreenOn: 'Plein écran activé.',
      fullscreenOff: 'Plein écran désactivé.',
      fullscreenUnsupported: 'Plein écran indisponible ici.',
      backgroundSync: 'Synchronisation en arrière-plan',
      backgroundSyncOn: 'Les exports différés seront réessayés automatiquement.',
      backgroundSyncOff: 'Indisponible — les exports seront réessayés à la prochaine ouverture.',
      wakeLock: 'Verrouillage de l’écran',
      wakeLockOn: 'L’écran reste actif pendant un quart en cours.',
      wakeLockOff: 'Verrouillage d’écran indisponible.',
      fileSystem: 'Accès au système de fichiers',
      fileSystemOn: 'Choisir l’emplacement de sauvegarde des rapports.',
      fileSystemOff: 'Retombe sur le dossier de téléchargement.',
      shareTarget: 'Cible de partage',
      shareTargetOn: 'D’autres apps peuvent partager du texte vers Macadam.',
      shareTargetOff: 'La cible de partage s’active une fois installé en PWA.',
      shareIntentTitle: 'Contenu partagé reçu',
      shareIntentBody: '{title} {text}',
    },
    zones: {
      sectionTitle: 'Gestion des zones',
      sectionLead: 'Renommer, fusionner ou retirer des étiquettes de zone sur tous les quarts.',
      emptyTitle: 'Aucune zone étiquetée',
      emptyMessage: 'Ajoutez une étiquette de zone sur un quart pour commencer.',
      tableHeader: {
        zone: 'Zone',
        shifts: 'Quarts',
        gross: 'Brut',
        hourly: 'Taux/h',
        perKm: 'Par km',
        expenses: 'Dépenses imputées',
        actions: 'Actions',
      },
      rename: 'Renommer',
      renameTitle: 'Renommer la zone',
      renameLabel: 'Nouveau nom',
      mergeTitle: 'Fusionner les zones',
      mergeInto: 'Fusionner vers',
      mergeAction: 'Fusionner la sélection',
      mergeHelp: 'Sélectionnez au moins deux lignes pour les fusionner.',
      delete: 'Effacer l’étiquette',
      deleteConfirmTitle: 'Effacer l’étiquette de zone ?',
      deleteConfirmMessage: 'Les quarts conservent leurs données; seule l’étiquette {zone} est retirée.',
      renamedToast: '{count} quarts renommés.',
      mergedToast: '{count} quarts fusionnés.',
      clearedToast: 'Étiquette retirée de {count} quarts.',
      unallocated: 'Non imputé (aucun quart ce jour-là)',
    },
    reports: {
      title: 'Rapports',
      export: 'Exporter',
      csv: 'CSV',
      json: 'JSON',
      print: 'Version imprimable',
      yearInReview: 'Bilan de l’année',
    },
    schedule: {
      title: 'Horaire',
      subtitle: 'Planification et calendrier',
      weekView: 'Semaine',
      monthView: 'Mois',
      timeBlock: 'Bloc de temps',
      planningMode: 'Mode planification',
    },
    search: {
      title: 'Recherche',
      placeholder: 'Rechercher quarts et dépenses',
      filter: 'Filtres',
      noResults: 'Aucun résultat',
    },
    modules: {
      onboarding: {
        title: 'Module d’accueil',
        body: 'Texte d’orchestration en phase 2 (`modules/onboarding/`).',
      },
      platforms: {
        title: 'Module plateformes',
        body: 'Sélecteur et config par plateforme en phase 2 (`modules/platforms/`).',
      },
      shifts: {
        title: 'Module quarts',
        body: 'CRUD, chronomètre et formulaires en phase 2 (`modules/shifts/`).',
      },
      expenses: {
        title: 'Module dépenses',
        body: 'Catégories et récurrence en phase 2 (`modules/expenses/`).',
      },
      analytics: {
        title: 'Module analytique',
        body: 'Agrégations et graphiques en phase 2 (`modules/analytics/`).',
      },
      tax: {
        title: 'Module fiscal',
        body: 'Feuilles par région en phase 2 (`modules/tax/`).',
      },
      vehicles: {
        title: 'Module véhicules',
        body: 'Garage et coûts en phase 2 (`modules/vehicles/`).',
      },
      goals: {
        title: 'Module objectifs',
        body: 'Badges, XP et séries en phase 2 (`modules/goals/`).',
      },
      reports: {
        title: 'Module rapports',
        body: 'Exports CSV/JSON/impression/QR en phase 2 (`modules/reports/`).',
      },
      search: {
        title: 'Module recherche',
        body: 'Intégration Fuse.js en phase 2 (`modules/search/`).',
      },
      notifications: {
        title: 'Module notifications',
        body: 'Tous les types de notifications en phase 2 (`modules/notifications/`).',
      },
      schedule: {
        title: 'Module horaire',
        body: 'Calendrier et planification en phase 2 (`modules/schedule/`).',
      },
      settings: {
        title: 'Module paramètres',
        body: 'Préférences complètes en phase 2 (`modules/settings/`).',
      },
    },
    views: {
      dashboard: {
        title: 'Tableau de bord',
        greeting: 'Voici votre aperçu',
        placeholderBody: 'Widgets et texte du tableau de bord en phase 2 (`views/dashboard.js`).',
      },
      shifts: {
        title: 'Quarts',
        subtitle: 'Enregistrez vos quarts, démarrez un chronomètre et importez votre historique',
        placeholderBody: 'Liste et filtres en phase 2 (`views/shifts-view.js`).',
      },
      analytics: {
        title: 'Analytique',
        placeholderBody: 'Mise en page analytique en phase 2 (`views/analytics-view.js`).',
      },
      tax: {
        title: 'Impôts',
        placeholderBody: 'Texte de la vue fiscale en phase 2 (`views/tax-view.js`).',
      },
      vehicles: {
        title: 'Véhicules',
        placeholderBody: 'Texte de la vue véhicules en phase 2 (`views/vehicles-view.js`).',
      },
      schedule: {
        title: 'Horaire',
        placeholderBody: 'Texte de la vue horaire en phase 2 (`views/schedule-view.js`).',
      },
      goals: {
        title: 'Objectifs',
        placeholderBody: 'Texte de la vue objectifs en phase 2 (`views/goals-view.js`).',
      },
      reports: {
        title: 'Rapports',
        placeholderBody: 'Texte de la vue rapports en phase 2 (`views/reports-view.js`).',
      },
      settings: {
        title: 'Paramètres',
        placeholderBody: 'Texte de la vue paramètres en phase 2 (`views/settings-view.js`).',
      },
      onboarding: {
        title: 'Accueil',
        placeholderBody: 'Coquille d’accueil en phase 2 (`views/onboarding-view.js`).',
      },
      about: {
        title: 'À propos de Macadam',
        placeholderBody:
          'Les données restent sur votre appareil. Récit complet et liens d’export en phase 2.',
      },
      print: {
        title: 'Impression',
        placeholderBody: 'Mises en page imprimables en phase 2 (`modules/reports/`).',
      },
      search: {
        title: 'Recherche',
        placeholderBody: 'Recherche floue en phase 2 (`modules/search/`).',
      },
    },
    ui: {
      modal: {
        close: 'Fermer',
      },
      confirm: {
        title: 'Confirmer ?',
        destructive: 'Cette action est difficile à annuler.',
        typeToConfirm: 'Tapez {value} pour confirmer',
      },
      toast: {
        success: 'Enregistré',
        error: 'Erreur',
        warning: 'Attention',
        info: 'Info',
        celebration: 'Bravo',
        dismiss: 'Ignorer',
      },
      fab: {
        addShift: 'Ajout rapide de quart',
        endShift: 'Terminer le quart',
      },
      drawer: {
        close: 'Fermer',
      },
      progressRing: {
        label: 'Progrès',
      },
      skeleton: {
        loading: 'Chargement',
      },
      emptyState: {
        defaultTitle: 'Rien pour l’instant',
        defaultMessage: 'Ajoutez un élément ou modifiez les filtres.',
      },
      keypad: {
        title: 'Saisir un montant',
        confirm: 'OK',
        clear: 'Effacer',
        backspace: 'Retour arrière',
        open: 'Clavier',
      },
    },
  },
};

/**
 * @param {string} key dot notation, e.g. `shifts.addShift`
 * @param {'en'|'fr'} [lang='en']
 * @returns {string} never `undefined`; missing keys fall back to English then to `key`
 */
export function t(key, lang = 'en') {
  const parts = String(key).split('.').filter(Boolean);
  const walk = (root) => {
    let cur = root;
    for (const p of parts) {
      if (cur == null || typeof cur !== 'object') return null;
      cur = cur[p];
    }
    return typeof cur === 'string' ? cur : null;
  };
  const primary = walk(strings[lang] || strings.en);
  if (primary != null) return primary;
  if (lang !== 'en') {
    const fallback = walk(strings.en);
    if (fallback != null) return fallback;
  }
  return String(key);
}
