/**
 * All user-facing copy (Feature 258 — `fr` mirrors `en` keys exactly).
 *
 * F7 structure: app, common, onboarding, shifts, analytics, notifications, errors,
 * vehicles, expenses, platforms, tax, goals, settings, reports, schedule, search,
 * plus `modules` / `views` / `ui` placeholders aligned to `docs/plan.md` file tree and F8 shell.
 * Leaf values are always strings so `t('a.b.c')` resolves to a string (fallback: English, then key).
 * Module-specific marketing copy and long-form help: Phase 2+ modules will replace placeholder text.
 */

/** @type {Record<'en'|'fr', Record<string, unknown>>} */
export const strings = {
  en: {
    app: {
      name: 'COMMA',
      tagline: 'Gig earnings, local-first',
      updateAvailable: 'App updated — reload for latest version',
      reload: 'Reload',
      offlineBanner: 'You are offline. Changes sync when you reconnect.',
      online: 'Online',
      offline: 'Offline',
      navDashboard: 'Dashboard',
      navShifts: 'Shifts',
      navAnalytics: 'Analytics',
      navExpenses: 'Expenses',
      navGoals: 'Goals',
      navSettings: 'Settings',
      navTax: 'Tax',
      navVehicles: 'Vehicles',
      navSchedule: 'Schedule',
      navReports: 'Reports',
      navImport: 'Imports',
      navSearch: 'Search',
      navMore: 'More',
      platformAll: 'All',
      headerAria: 'App header',
      navAria: 'Main navigation',
      skipToContent: 'Skip to main content',
      demoModeBanner: 'Demo mode — 2025 sample shifts and expenses (three platforms), not your real data.',
      exitDemo: 'Exit demo',
      exitDemoToast: 'Vault cleared — reloading so you can set up COMMA from scratch.',
    },
    common: {
      save: 'Save',
      cancel: 'Cancel',
      close: 'Close',
      confirm: 'Confirm',
      all: 'All',
      sort: 'Sort',
      delete: 'Delete',
      edit: 'Edit',
      done: 'Done',
      back: 'Back',
      next: 'Next',
      loading: 'Loading…',
      optional: 'Optional',
      required: 'Required',
      yes: 'Yes',
      no: 'No',
      copy: 'Copy',
      share: 'Share',
      retry: 'Retry',
      warning: 'Warning',
      ok: 'OK',
    },
    provinces: {
      on: 'Ontario',
      us: { state: 'State' },
    },
    onboarding: {
      title: 'Welcome to COMMA',
      subtitle: 'Track gig earnings in one place',
      continue: 'Continue',
      skip: 'Skip for now',
      finish: 'Get started',
      stepProgress: 'Step {current} of {total}',
      welcomeTitle: 'Welcome',
      platformsTitle: 'Which platforms do you use?',
      vehicleTitle: 'Your vehicle',
      goalsTitle: 'Weekly goal',
      notificationsTitle: 'Stay on track',
      privacyTitle: 'Privacy',
      summaryTitle: 'You are set',
      placeholderBody:
        'Onboarding step copy is finalized in Phase 2 (orchestrator + steps.js). Keys exist so `t()` stays stable.',
      tryDemo: 'Try demo first',
      landing: {
        kicker: 'Local-first gig earnings',
        heroTitle: 'Your gig data, private by design.',
        heroLead:
          'COMMA is a privacy-first gig earnings and expense tracker for multi-app drivers. Securely log shifts, track your week, and get tax-ready snapshots — all stored locally on your device.',
        startCta: 'Start onboarding',
        restoreLink: 'Restore existing vault',
        privacyLink: 'Privacy Policy',
        screenshotsTitle: 'See some snapshots below',
        sectionTitle: 'What COMMA does for you',
        featVaultTitle: 'Private vault',
        featVaultBody:
          'No account needed. Your data stays on your device, and you can securely back it up to your own Google Drive whenever you want.',
        featShiftsTitle: 'Shift timeline',
        featShiftsBody:
          'Capture platforms, hours, distance, tips, and bonuses in one place so nothing slips through the cracks.',
        featTaxTitle: 'Tax-minded totals',
        featTaxBody:
          'Set a withholding habit and see rough net figures so April does not feel like a surprise.',
        featGoalsTitle: 'Goals & momentum',
        featGoalsBody:
          'Weekly targets, streaks, and simple charts help you pace yourself without spreadsheet fatigue.',
        footnote: 'Setup takes a few minutes. Prefer a tour first? Try the demo — a full sample year you can clear anytime.',
      },
      demoEnabled: 'Demo vault loaded. Explore 2025 sample data.',
      resumeTitle: 'Continue setup?',
      resumeMessage: 'You started onboarding earlier this session. Continue where you left off, or start over.',
      resumeContinue: 'Continue',
      resumeStartOver: 'Start over',
      completeToast: 'Your vault is ready. Welcome aboard!',
      exportDone: 'Setup file downloaded.',
      resetNeedExport: 'Export a backup before resetting the vault.',
      resetTitle: 'Reset vault',
      resetMessage: 'This deletes all local COMMA data on this device. Export a backup first.',
      resetConfirm: 'Reset everything',
      motivation: {
        high: 'Strong target — we will cheer you on every week.',
        mid: 'Solid goal — great balance of stretch and realism.',
        low: 'Gentle ramp — you can raise it anytime in Goals.',
        start: 'Every journey starts with a single shift logged.',
      },
      schedule: {
        flexible: 'Flexible hours',
        weekdays: 'Mostly weekdays',
        evenings: 'Evenings',
        weekends: 'Weekends',
      },
      theme: { light: 'Light', dark: 'Dark', auto: 'Auto' },
      vehicleTypes: {
        gas: 'Gas vehicle',
        hybrid: 'Hybrid',
        ev: 'Electric',
        motorcycle: 'Motorcycle',
        bicycle: 'Bicycle',
        ebike: 'E-bike',
        scooter: 'Scooter',
        walking: 'Walking',
      },
      steps: {
        platformsTitle: 'Which platforms do you use?',
        platformsLead:
          'Select every gig or delivery app you earn through—including if you walk or bike. You can change this anytime in Settings.',
        platformsLeadFiltered: 'Only platforms available for your region are shown (from the province registry).',
        noPlatformsForRegion: 'No platforms are registered for this region yet. Try another region or contact support.',
        profileTitle: 'How should we greet you?',
        profileLead: 'This name appears on your dashboard and exports.',
        driverName: 'Your name',
        avatarPick: 'Avatar',
        avatarInitials: 'Use initials',
        avatarCustom: 'Upload a photo',
        avatarUpload: 'Choose image',
        avatarUploadHint: 'Square image works best (max 500KB)',
        regionTitle: 'Country or region',
        regionLead: 'We set currency, distance defaults, and tax hints from here.',
        chooseCountryTitle: 'Which country do you drive in?',
        chooseCountryLead: 'Currency and distance units follow your market.',
        chooseRegionTitle: 'Province, state, or region',
        chooseRegionLead: 'Tax presets and catalog data use this where your country is supported.',
        regionShortLabel: 'Region',
        regionOptionalLead: 'Optional — a short code is enough if you want it on exports.',
        ontarioTitle: 'Ontario, Canada',
        ontarioLead: 'COMMA v3 is built for Ontario gig drivers first — CAD, kilometres, and provincial tax defaults.',
        country: 'Country',
        countryCA: 'Canada',
        countryUS: 'United States',
        countryUK: 'United Kingdom',
        currencyHint: 'Currency',
        vehicleTitle: 'Primary vehicle',
        vehicleLead: 'Fuel or EV details unlock smarter cost estimates later.',
        vehicleNickname: 'Nickname',
        vehicleType: 'Vehicle type',
        make: 'Make',
        model: 'Model',
        year: 'Year',
        secondVehicleTitle: 'Another vehicle?',
        secondVehicleLead: 'Optional — useful if you switch between car and bike.',
        addAnotherVehicle: 'Add a second vehicle',
        homeBaseTitle: 'Home base zone',
        homeBaseLead: 'A short label for the area you usually start from.',
        homeBaseLabel: 'Zone label',
        homeBasePlaceholder: 'e.g. Downtown, North End',
        scheduleTitle: 'Typical schedule',
        scheduleLead: 'Helps with reminders and planning views.',
        weeklyGoalTitle: 'Weekly earnings goal',
        weeklyGoalLead: 'We use this for the goal ring and weekly nudges.',
        weeklyGoalLabel: 'Target gross per week',
        longTermGoalsTitle: 'Monthly and annual targets',
        longTermGoalsLead: 'Prefilled from your weekly goal — adjust freely.',
        monthlyGoal: 'Monthly target',
        annualGoal: 'Annual target',
        taxTitle: 'Tax set-aside',
        taxLead: 'Rough percentage to set aside from gross for taxes.',
        province: 'Province or territory',
        state: 'State',
        taxRegionPlaceholder: 'Select…',
        taxWithholding: 'Withholding %',
        applyPreset: 'Apply region preset',
        hstTitle: 'GST / HST registration',
        hstLead: 'Canada only — affects HST worksheets later.',
        hstToggle: 'I collect or remit GST / HST',
        hstSkip: 'GST / HST does not apply for your selected country.',
        distanceTitle: 'Distance units',
        distanceLead: 'Shown on shifts, mileage, and maps.',
        unitKm: 'Kilometres',
        unitMi: 'Miles',
        themeTitle: 'Appearance',
        themeLead: 'You can change this anytime in Settings.',
        notifyTitle: 'Notifications',
        notifyLead: 'All local — we never upload your shifts.',
        completeTitle: 'Your vault is ready, {name}',
        completeFallbackName: 'driver',
        completeLead: 'Export a tiny setup file, try sample data, or head straight in.',
        enterVault: 'Enter my vault',
        exportSetup: 'Save setup to file',
      },
      why: {
        platformsSummary: 'Why we ask',
        platformsBody:
          'We use your choices to match labels, colors, and filters to the services you actually work with.',
        profileSummary: 'Why we ask',
        profileBody: 'Exports and summaries read better with your name and a recognizable avatar.',
        regionSummary: 'Why we ask',
        regionBody: 'Currency and mileage rules follow your country so numbers stay trustworthy.',
        vehicleSummary: 'Why we ask',
        vehicleBody: 'Vehicle type unlocks the right cost fields when we estimate per-shift expenses.',
        secondVehicleSummary: 'Why we ask',
        secondVehicleBody: 'Many drivers switch vehicles by day; two profiles keep mileage honest.',
        homeBaseSummary: 'Why we ask',
        homeBaseBody: 'Zone tags help you spot which areas pay best over time.',
        scheduleSummary: 'Why we ask',
        scheduleBody: 'We schedule gentle reminders around the times you actually drive.',
        weeklyGoalSummary: 'Why we ask',
        weeklyGoalBody: 'A visible target keeps earnings momentum without judgment.',
        longTermGoalsSummary: 'Why we ask',
        longTermGoalsBody: 'Longer horizons smooth out slow weeks and busy seasons.',
        taxSummary: 'Why we ask',
        taxBody: 'This is guidance only — not tax advice. It powers set-aside reminders.',
        hstSummary: 'Why we ask',
        hstBody: 'Registered collectors have different worksheets than drivers who only earn T4-style income.',
        distanceSummary: 'Why we ask',
        distanceBody: 'Platforms mix km and miles; we store one consistent unit for you.',
        themeSummary: 'Why we ask',
        themeBody: 'Comfortable contrast matters when you log shifts at night.',
        notifySummary: 'Why we ask',
        notifyBody: 'You stay in control — everything runs locally in this browser.',
      },
      notify: {
        shiftReminders: 'Shift reminders',
        goalAlerts: 'Goal progress nudges',
        taxReminders: 'Tax deadline reminders',
        weeklyDigest: 'Weekly summary email (local draft only)',
      },
      validation: {
        platforms: 'Pick at least one platform.',
        platformsNone: 'No platforms are available for this region in the catalog.',
        name: 'Please enter your name.',
        country: 'Choose a country.',
        region: 'Choose a province, state, or region.',
        vehicle: 'Add a nickname and vehicle type.',
        secondVehicle: 'Fill in the second vehicle or turn off “add another”.',
        tax: 'Enter a withholding percentage between 0 and 80.',
      },
      sample: {
        load: 'Load a full 2025 demo year (shifts + expenses, three platforms)',
        loaded: '2025 demo data added — shifts are placeholders; expenses are tagged in notes.',
      },
    },
    shifts: {
      addShift: 'Add shift',
      editShift: 'Edit shift',
      deleteShift: 'Delete shift',
      duplicateShift: 'Duplicate shift',
      endShift: 'End shift',
      startShift: 'Start shift',
      shiftTimer: 'Shift timer',
      savedToast: 'Shift saved',
      deletedToast: 'Shift moved to trash',
      restoredToast: 'Shift restored',
      undo: 'Undo',
      timerStarted: 'Shift timer started',
      timerNotRunning: 'No active shift timer',
      template: 'Template',
      templates: 'Templates',
      noTemplates: 'No templates yet.',
      saveAsTemplate: 'Save as template',
      templateName: 'Template name',
      templateNamePlaceholder: 'e.g. Dinner rush',
      purgeTrash: 'Purge trash',
      purgedToast: 'Trash purged',
      trash: 'Trash',
      noTrash: 'Trash is empty.',
      restore: 'Restore',
      bulkImport: 'Bulk import',
      importLead: 'Upload a CSV to import shifts. Preview shows the first 5 rows.',
      importPreview: 'Preview (first 5 rows)',
      importAppend: 'Append',
      importReplace: 'Replace all',
      importParseError: 'Could not parse CSV.',
      importValidationFailed: 'CSV Validation Failed',
      importDone: 'Imported {count} shifts.',
      notes: 'Notes',
      notesPlaceholder: 'Optional notes…',
      gross: 'Gross',
      net: 'Net',
      expenses: 'Expenses',
      duration: 'Duration',
      orders: 'Orders',
      tips: 'Tips',
      bonus: 'Bonus',
      distance: 'Distance',
      deadMiles: 'Dead miles (km)',
      deadMilesRatio: 'Dead miles ratio',
      unitKm: 'km',
      unitMiles: 'miles',
      date: 'Date',
      startTime: 'Start time',
      endTime: 'End time',
      advancedToggle: 'Basic / Advanced',
      onlineMinutes: 'Online minutes',
      activeMinutes: 'Active minutes',
      vehicle: 'Vehicle',
      vehicleNone: 'No vehicle',
      vehicleEstimate: 'Vehicle estimate',
      weather: 'Weather',
      weatherClear: 'Clear',
      weatherRain: 'Rain',
      weatherSnow: 'Snow',
      weatherFog: 'Fog',
      weatherHeat: 'Heat',
      zone: 'Zone',
      zonePlaceholder: 'e.g. Downtown',
      mood: 'Mood',
      platform: 'Platform',
      platformExtras: 'Platform details',
      psObjectHint: 'JSON object — invalid JSON keeps the previous value.',
      psCOMMAPlaceholder: 'COMMA-separated values',
      ps: {
        peakPay: 'Peak pay',
        dashZone: 'Dash zone',
        acceptanceRate: 'Acceptance rate (%)',
        customerRating: 'Customer rating',
        surgeMultiplier: 'Surge multiplier',
        proStatus: 'Pro status',
        completionRate: 'Completion rate (%)',
        questOnlineMinutes: 'Quest online minutes',
        orderTypeSplit: 'Order type split (JSON)',
        attendanceScore: 'Attendance score',
        creditsPromos: 'Credits / promos',
        cityScore: 'City score',
        batchCount: 'Batch count',
        batchTypes: 'Batch types (comma-separated)',
        blockDurationMinutes: 'Block duration (minutes)',
        blockType: 'Block type',
      },
      emptyTitle: 'No shifts yet',
      emptyMessage: 'Log your first shift to see earnings and trends.',
      deleteConfirm: 'Delete this shift? This cannot be undone.',
      filterPresetsAria: 'Quick date filters',
      presetWeek: 'Week',
      presetYtd: 'YTD',
      presetAll: 'All',
      rangeStart: 'Range start',
      rangeEnd: 'Range end',
      rangeLabel: 'Date range',
      headerToolsAria: 'Shifts tools',
      rangeApply: 'Apply',
      sortByDate: 'Sort',
      sortNewest: 'Newest first',
      sortOldest: 'Oldest first',
      pagePrev: 'Previous',
      pageNext: 'Next',
      pageStatus: 'Page {current} of {total}',
      pagerAria: 'Shift list pages',
      entryScopeLabel: 'Entry type',
      entryOneDay: 'One day',
      entryWeekDays: 'Multiple days',
      weekContaining: 'Week containing',
      weekDaysHint: 'Days to include when saving',
      weekSaveHint: 'The same details are saved once per included day (handy for a routine week). Days that conflict with an existing shift may be skipped.',
      weekNoDays: 'Select at least one day.',
      savedManyToast: 'Saved {count} shifts',
      weekPartialToast: 'Saved {ok} shifts; {skip} skipped.',
      emptyFilteredTitle: 'No shifts in this range',
      emptyFilteredMessage: 'Try a wider date range or different filters.',
      kpiNet: 'Net Income',
      sections: {
        insights: 'Business Insights',
      },
    },
    analytics: {
      title: 'Analytics',
      subtitle: 'Earnings, pace, and patterns',
      hourlyRate: 'Hourly rate',
      netHourly: 'Net hourly',
      earnings: 'Earnings',
      distance: 'Distance',
      tips: 'Tips',
      bonus: 'Bonus',
      orders: 'Orders',
      zones: 'Zones',
      trends: 'Trends',
      heatmap: 'Heatmap',
      scatter: 'Scatter',
      byDayOfWeek: 'By day of week',
      byHour: 'By hour of day',
      utilization: 'Utilization',
      records: 'Personal records',
      projection: 'Week projection',
      streak: 'Streak',
      compare: 'Compare periods',
      recentActivity: 'Recent activity',
      topShifts: 'Top earning shifts',
      zeroDays: 'Zero days',
      bestWindow: 'Best windows',
      bestDay: 'Best day',
      bestHour: 'Best hour',
      deadMilesSummary: 'Dead miles',
      deadKmOfTotal: 'of distance',
      deadKmUnits: 'km dead-head',
      deadMilesRatio: 'Dead miles % of trip',
      lastPeriod: 'Last week',
      thisPeriod: 'This week',
      baseIncome: 'Base',
      earningsVsHours: 'Earnings vs Hours',
      emptyTitle: 'Not enough data yet',
      emptyMessage: 'Log a few shifts to unlock charts and insights.',
      
      // New Sync & Insight Strings
      performanceModules: 'Performance Modules',
      deepInsights: 'Deep Insights',
      statModules: 'Summary Stats',
      addToDashboard: 'Add to Dashboard',
      onDashboard: 'On Dashboard',
      addedToDashboard: 'Added to dashboard',
      
      // Widget specific labels (if needed by i18n helper)
      platformActivity: 'Platform Mix',
      incomeBreakdown: 'Income Breakdown',
      basePay: 'Base Pay',
      tipsLabel: 'Tips',
      bonusPromo: 'Bonus / Promo',
      weeklyProjection: 'Weekly Projection',
      projectionLead: 'Estimated total for this week.',
      stabilityScore: 'Stability Score',
      stabilityLead: 'How consistent your weekly earnings are.',
    },
    notifications: {
      title: 'Notifications',
      permissionDenied: 'Notifications are blocked in this browser.',
      enableHint: 'Enable notifications to get shift reminders and nudges.',
      reminderShift: 'Shift reminder',
      goalMet: 'Goal reached',
      taxDeadline: 'Tax deadline approaching',
      weeklySummary: 'Weekly summary',
      openSettings: 'Open settings',
    },
    errors: {
      generic: 'Something went wrong. Try again.',
      offline: 'You appear to be offline.',
      network: 'Network request failed. Check your connection.',
      dbOpen: 'Could not open local database.',
      dbMigration: 'Database upgrade failed.',
      invalidInput: 'Check your entries and try again.',
      notFound: 'That item could not be found.',
      permission: 'Permission denied.',
      importFailed: 'Import failed. Check the file format.',
      exportFailed: 'Export failed. Try again.',
      viewRender: 'This screen could not be loaded.',
      storeBindMissing: 'Store bind: element not found.',
      backupDemoWarning: 'Demo mode does not support cloud sync.',
    },
    vehicles: {
      title: 'Vehicles',
      add: 'Add vehicle',
      edit: 'Edit vehicle',
      fuel: 'Fuel',
      ev: 'Electric',
      maintenance: 'Maintenance',
      mileage: 'Mileage',
      depreciation: 'Depreciation',
      efficiency: 'Efficiency',
      subtitle: 'Vehicle profiles, mileage logs, upkeep reminders, and per-km economics.',
      emptyTitle: 'No vehicles yet',
      emptyMessage: 'Add your first vehicle to unlock mileage and cost tracking.',
    },
    expenses: {
      title: 'Expenses',
      add: 'Add expense',
      editTitle: 'Edit expense',
      subtitle: 'Track fuel, maintenance, and business costs',
      category: 'Category',
      categories: {
        fuel: 'Fuel',
        maintenance: 'Maintenance',
        parking: 'Parking',
        tolls: 'Tolls',
        insurance: 'Insurance',
        registration: 'Registration',
        phone: 'Phone',
        data_plan: 'Data plan',
        car_wash: 'Car wash',
        supplies: 'Supplies',
        meals: 'Meals',
        bank_fees: 'Bank fees',
        software: 'Software',
        accounting: 'Accounting',
        other: 'Other',
      },
      /** Province `labelKey` paths (e.g. ON.province.js); keep ids aligned with `categories`. */
      cat: {
        fuel: 'Fuel',
        maintenance: 'Maintenance',
        parking: 'Parking',
        tolls: 'Tolls',
        insurance: 'Insurance',
        registration: 'Registration',
        phone: 'Phone',
        data_plan: 'Data plan',
        car_wash: 'Car wash',
        supplies: 'Supplies',
        meals: 'Meals',
        bank_fees: 'Bank fees',
        software: 'Software',
        accounting: 'Accounting',
        bike_maintenance: 'Bike / e-bike maintenance',
        other: 'Other',
      },
      uncategorized: 'Uncategorized',
      amount: 'Amount',
      date: 'Date',
      platformAssignment: 'Platform',
      businessUsePct: 'Business use %',
      businessUseLabel: '{pct}% used for delivery work',
      notes: 'Notes',
      notesPlaceholder: 'Optional note…',
      receipt: 'Receipt',
      receiptHint: 'Upload a receipt photo (saved locally).',
      receiptAttached: 'Receipt attached.',
      recurring: 'Recurring',
      recurringInterval: 'Recurring interval',
      recurringWeekly: 'Weekly',
      recurringMonthly: 'Monthly',
      recurringAnnual: 'Annual',
      hstItc: 'HST / ITC amount',
      confirmedPaid: 'I already paid this recurring expense',
      savedToast: 'Expense saved',
      deletedToast: 'Expense deleted',
      autoExpenseTitle: 'Fuel expense from shift',
      autoExpenseTitleEv: 'Charging expense from shift',
      autoExpenseNote: 'Suggested from shift #{shiftId}',
      confirmAutoExpense: 'Save expense',
      fuelExpenseToast: 'Estimated fuel for this shift: {amount}.',
      fuelExpenseToastEv: 'Estimated charging cost for this shift: {amount}.',
      addExpenseToastAction: 'Add expense',
      tabAll: 'All',
      tabByCategory: 'By category',
      tabRecurring: 'Recurring',
      tabDeductions: 'Deductions',
      byCategoryHint: 'Totals use the same filters as the All tab (business-use portion).',
      categoryTotalHeader: 'Total',
      recurringPanelHint: 'Recurring templates and their next due date.',
      recurringNextDue: 'Next due',
      recurringAmount: 'Amount',
      recurringEditTitle: 'Log this payment',
      recurringPromptTitle: 'Recurring expense due',
      recurringPromptBody: '{category} — {amount} — due {date}. Did you pay it?',
      recurringYesPaid: 'Yes, paid',
      recurringEditAmount: 'Edit amount',
      recurringSkip: 'Skip for now',
      deductionsTitle: 'Deductions & tax',
      deductionsLead: 'Business-use % and tax deductions are managed from the Tax workspace.',
      deductionsGoTax: 'Open Tax',
      filterStartDate: 'Start date',
      filterEndDate: 'End date',
      minAmount: 'Min amount',
      maxAmount: 'Max amount',
      receiptOnly: 'Has receipt',
      sortDateDesc: 'Date (newest)',
      sortDateAsc: 'Date (oldest)',
      sortAmountDesc: 'Amount (high to low)',
      sortAmountAsc: 'Amount (low to high)',
      sortCategory: 'Category (A-Z)',
      sortPlatform: 'Platform (A-Z)',
      emptyTitle: 'No expenses yet',
      emptyMessage: 'Track fuel, maintenance, and other gig costs here.',
      addNewExpense: 'Add new expense',
      recordsTitle: 'Expense records',
      searchPlaceholder: 'Search…',
      rowsPerPage: 'Rows per page',
      rowsOption: '{n} rows',
      resetFilters: 'Reset',
      moreFilters: 'More filters',
      kpiTotal: 'Total expenses',
      kpiCount: 'Total count',
      kpiAverage: 'Average per expense',
      kpiCategories: 'Categories',
      chartByCategory: 'Expenses by category',
      chartMonthlyTrend: 'Monthly expenses trend',
      columnDescription: 'Description',
      columnActions: 'Actions',
      sortAria: 'Sort by {column}',
      totalsLabel: 'Totals',
      totalsExpensesCount: '{n} expenses',
      pageInfo: 'Page {page} / {pages} ({total} rows)',
      previousPage: 'Previous',
      nextPage: 'Next',
    },
    platforms: {
      title: 'Platforms',
      switcher: 'Filter',
      add: 'Add Platform',
      config: 'Platform Settings',
      terminology: 'Terms',
      settingsSectionTitle: 'Platforms',
      settingsSectionLead: 'Apps, goals, and layout.',
      switcherMode: 'Switcher style',
      switcherTabs: 'Tabs',
      switcherDropdown: 'Dropdown',
      switcherTabsCompactHint: '',
      switcherModeSaved: 'Switcher updated.',
      weeklyGoal: 'Weekly goal ($)',
      monthlyGoal: 'Monthly goal ($)',
      taxRate: 'Tax rate override (%)',
      notes: 'Notes',
      helpLink: 'Help center',
      apiDisclaimer: 'No external connections. Data stays on-device.',
      deactivate: 'Deactivate',
      deactivateTitle: 'Deactivate platform?',
      deactivateMessage: 'Historical shifts for {name} stay in your vault. You can add this platform again later.',
      deactivated: 'Platform deactivated.',
      lastActive: 'Keep at least one active platform.',
      saved: 'Platform settings saved.',
      noInactive: 'Every catalog platform is already active.',
      pickPlatform: 'Choose a platform…',
      added: 'Platform added.',
      reactivate: 'Turn back on',
      reactivated: 'Platform reactivated.',
      inactiveHeading: 'Inactive platforms',
      cardMeta: 'Per-platform targets and notes',
      otherExplain: 'Name and color appear in the switcher and reports.',
      otherName: 'Display name',
      otherColor: 'Accent color',
      activateOtherTitle: 'Set up “Other”',
    },
    tax: {
      title: 'Tax',
      subtitle: 'Planning, set-aside, and snapshots.',
      taxYear: 'Tax year',
      virtualJar: 'Tax set-aside tracker',
      targetSetAside: 'Target set-aside',
      currentSetAside: 'Current set-aside',
      hstCollectedTracker: 'HST/GST collected',
      itcTracker: 'Input tax credits (ITC)',
      collected: 'Collected',
      remittable: 'Estimated remittable',
      incomeSnapshot: 'Income snapshot',
      grossIncome: 'Gross income',
      businessExpenses: 'Business expenses',
      netIncome: 'Net income',
      netAfterSetAside: 'Net after set-aside',
      netIncomeNote: 'Net income is gross earnings minus business expenses. The set-aside amount is reserved for taxes and does not change your taxable income.',
      withholdingSettings: 'Withholding settings',
      provinceStatePresets: 'Province/state tax rate presets',
      province: 'Province',
      state: 'State',
      applyPreset: 'Apply preset to profile',
      currentRate: 'Current withholding rate',
      presetApplied: 'Tax rate updated to {rate}.',
      mileageDeduction: 'Mileage and cost comparison',
      totalDistance: 'Business distance',
      standardMileage: 'Standard mileage method',
      actualCost: 'Actual cost method',
      vehicleActualCosts: 'Vehicle actual costs',
      actualCostsNote:
        'Self-employed gig income in Canada uses actual vehicle expenses (fuel, maintenance, insurance, etc.) with business-use percentage — not the CRA standard mileage rate.',
      kilometres: 'km',
      miles: 'mi',
      cppEstimator: 'CPP estimator (Canada)',
      seTaxEstimator: 'Self-employment tax estimator (US)',
      estimatedValue: 'Estimated annual amount',
      cppNote: 'Planning estimate only; verify with CRA worksheets.',
      seTaxNote: 'Planning estimate only; verify with IRS worksheets.',
      installmentDeadlines: 'Installment deadlines',
      overdue: 'overdue',
      t2125: {
        title: 'T2125 helper (Canada)',
        grossIncome: 'Part 3A — Gross business income',
        advertising: 'Line 8521 — Advertising',
        meals: 'Line 8523 — Meals and entertainment',
        motorVehicle: 'Line 9281 — Motor vehicle expenses',
        supplies: 'Line 8811 — Office expenses and supplies',
        other: 'Part 4 — Other deductible expenses',
        netIncome: 'Part 5 — Net business income',
      },
      scheduleC: {
        title: 'Schedule C helper (US)',
        partIIncome: 'Part I — Income',
        partIIExpenses: 'Part II — Expenses',
        carTruck: 'Line 9 — Car and truck expenses',
        depreciation: 'Line 13 — Depreciation',
        homeOffice: 'Line 30 — Home office deduction',
        other: 'Part V — Other expenses',
        netProfit: 'Line 31 — Net profit or loss',
      },
      referenceLinks: 'Official references',
      links: {
        businessIncomeGuide: 'Business income and expenses',
        scheduleCGuide: 'Schedule C guide',
        hstGuide: 'GST/HST for businesses',
        estimatedTaxes: 'Estimated taxes',
      },
      footnoteCanada: 'Not tax advice. Verify your filing with CRA guidance or a tax professional.',
      footnoteUs: 'Not tax advice. Verify your filing with IRS guidance or a tax professional.',
      footnoteGeneric: 'Not tax advice. Verify your filing with your local tax authority or a qualified professional.',
      genericEstimatorTitle: 'Contributions & levies (estimate)',
      genericEstimatorNote: 'Planning estimate only; rules vary by country — verify with official guidance.',
      exportSummary: 'Export tax summary',
      exportHint: 'Download this year summary as JSON or CSV.',
      exportJson: 'Export JSON',
      exportCsv: 'Export CSV',
      exportedJson: 'Tax summary JSON exported.',
      exportedCsv: 'Tax summary CSV exported.',
    },
    goals: {
      title: 'Goals',
      weeklyTarget: 'Weekly target',
      badges: 'Badges',
      xp: 'XP',
      challenges: 'Challenges',
      streakDays: 'Day streak',
      level: 'Level',
      weeksHit: 'Weeks hit',
      of: 'of',
      thermometer: 'Thermometer',
      activeGoals: 'Active goals',
      history: 'Goal history',
      to: 'to',
      hit: 'hit',
      inProgress: 'in progress',
    },
    settings: {
      title: 'Settings',
      subtitle: 'Personalize your COMMA experience',
      tabsAriaLabel: 'Sections',
      tabYou: 'You',
      tabAppearance: 'Appearance',
      tabPlatforms: 'Platforms',
      tabAlerts: 'Alerts',
      tabData: 'Vault',
      tabAbout: 'About',
      groupProfileTitle: 'Profile',
      groupLocationTitle: 'Market',
      groupLocationLead: 'Region, currency, and primary platform.',
      lookFeelSectionTitle: 'Interface',
      lookFeelSectionLead: 'Theme, fonts, and adaptive accent.',
      accentPresetsAria: 'Preset accent colors',
      accentPresetUse: 'Use accent',
      accentLabel: 'Accent color (adapts to active platform)',
      accentCustomHex: 'Custom hex',
      dashboardSectionTitle: 'Dashboard',
      dashboardSectionLead: 'Reorder widgets and hero stats.',
      dataVaultSectionTitle: 'Health & Backups',
      platformsSectionLead: 'Configure gig apps and goals.',
      language: 'Language',
      dateFormat: 'Date format',
      timeFormat: 'Time format',
      theme: 'Theme',
      distanceUnit: 'Distance unit',
      currency: 'Currency',
      notifications: 'Notifications',
      dataExport: 'Export data',
      dangerZone: 'Danger zone',
      about: 'About',
      shortcutsTitle: 'Keyboard shortcuts',
      shortcutsLead: 'Quick navigation and search combos (when focus is not in a text field).',
      dataSectionTitle: 'Vault',
      dataSectionLead: 'Manual JSON backups and storage health.',
      openReportsBtn: 'Open reports & exports',
      exportVaultBtn: 'Download vault JSON',
      exportVaultToast: 'Backup downloaded. A backup timestamp was saved for reset safety checks.',
      workspaceSectionTitle: 'Jump to workspace',
      workspaceSectionLead: 'Open any main screen from here (same routes as the bottom nav).',
      marketSectionTitle: 'Market',
      marketSectionLead: 'Regional tax defaults and units.',
      goalsTaxSectionTitle: 'Goals & Tax',
      goalsTaxSectionLead: 'Targets and withholding habit.',
      labelCountry: 'Country',
      labelDistanceUnit: 'Distance unit',
      labelPrimaryPlatform: 'Primary platform',
      primaryPlatformNone: 'No default',
      saveMarket: 'Update Market',
      marketSaved: 'Market and locale saved.',
      labelWeeklyGoalDollars: 'Weekly income target ($)',
      labelMonthlyGoalDollars: 'Monthly target ($)',
      labelAnnualGoalDollars: 'Annual target ($)',
      labelTaxWithhold: 'Tax set-aside %',
      labelWorkSchedule: 'Typical schedule',
      saveGoalsTax: 'Update Goals',
      goalsTaxSaved: 'Goals updated.',
      demoBanner: 'You are in demo mode — sample data resets when you leave.',
      exitDemoBtn: 'Exit demo',
      quickSnapshotBtn: 'Quick table snapshot',
      quickSnapshotToast: 'Snapshot downloaded and backup timestamp saved.',
      dangerSectionTitle: 'Danger zone',
      dangerSectionLead:
        'Erasing the vault removes all shifts, expenses, and settings from this browser after you type RESET to confirm. Export a backup first.',
      dangerResetBtn: 'Erase local vault…',
      aboutSectionTitle: 'About',
      aboutSectionLead: 'Product notes, community tips, and experimental polish.',
      aboutAppLink: 'Polish & community',
      aboutRouteLink: 'Build / route info',
      notificationsLead: 'System alerts and browser feature status.',
      dataVaultActions: 'Vault actions',
      dataMaintenance: 'Maintenance',
      shortcuts: {
        ctrlOrCmd: 'Ctrl / ⌘',
        searchCmdK: 'Open search',
        searchSlash: 'Open search (when not typing in a field)',
        escOverlays: 'Close overlays',
      },
      backupTitle: 'Cloud Backup',
      backupLead: 'Google Drive · App Data Folder',
      backupConnectBtn: 'Connect Google Drive',
      backupDisconnectBtn: 'Disconnect Drive',
      backupNowBtn: 'Back up now',
      backupRestoreBtn: 'Restore',
      backupStatusConnected: 'Connected',
      backupStatusDisconnected: 'Drive disconnected',
      backupStatusOffline: 'No internet connection',
      backupStatusOverdue: 'Backup overdue',
      backupStatusRecently: 'Backed up recently',
      backupStatusToday: 'Backed up today',
      backupStatusNone: 'No backup yet',
      backupStatusOfflineSub: 'Backup will resume when you\'re back online.',
      backupConnectSub: 'Your data stays on your device. Drive is optional.',
      backupStatusDisconnectedSub: 'Reconnect to resume automatic backups.',
      backupSuccessToast: 'Vault backed up to Drive ✓',
      backupFailToast: 'Backup failed',
      backupRestoreSuccessToast: 'Vault restored successfully ✓',
      backupRestoreFailToast: 'Restore failed',
      backupDemoWarning: 'This is demo mode. You cannot connect Drive here. Please exit demo and onboard with your own data.',
      backupRestoreTitle: 'Restore from Drive',
      backupRestoreSearching: 'Searching for backups...',
      backupRestoreEmpty: 'No backups found in your Google Drive.',
      backupRestoreConfirmTitle: 'Restore this backup?',
      backupRestoreConfirmMessage: 'This will REPLACE your current local data. Please ensure you have a manual export if you want to keep your current data.',
      backupRestoreConfirmText: 'Restore Vault',
      backupDisconnectConfirmTitle: 'Disconnect Google Drive?',
      backupDisconnectConfirmMessage: 'Automatic backups will stop. Your data remains in Drive but won\'t be updated.',
    },
    pwa: {
      sectionTitle: 'Device Features',
      sectionLead: 'Optional browser APIs and system permissions.',
      capabilityHeading: 'Capabilities detected',
      supported: 'Supported',
      unsupported: 'Not available in this browser',
      requestNotifications: 'Enable notifications',
      notificationsGranted: 'Notifications enabled',
      notificationsDenied: 'Notifications blocked by browser',
      notificationsUnsupported: 'Notifications are not available here',
      testVibrate: 'Test vibration',
      vibrationOk: 'Sent a quick haptic pulse.',
      vibrationUnsupported: 'This device cannot vibrate.',
      toggleFullscreen: 'Toggle fullscreen',
      fullscreenOn: 'Entered fullscreen.',
      fullscreenOff: 'Exited fullscreen.',
      fullscreenUnsupported: 'Fullscreen is not available here.',
      backgroundSync: 'Background Sync',
      backgroundSyncOn: 'Deferred exports will retry automatically.',
      backgroundSyncOff: 'Background Sync unavailable — exports retry on next open.',
      wakeLock: 'Screen Wake Lock',
      wakeLockOn: 'Screen stays awake during active shift timers.',
      wakeLockOff: 'Wake Lock not available in this browser.',
      fileSystem: 'File System Access',
      fileSystemOn: 'Choose where to save reports and backups.',
      fileSystemOff: 'Falls back to download folder.',
      shareTarget: 'Share Target',
      shareTargetOn: 'Other apps can share text into COMMA.',
      shareTargetOff: 'Share Target registers when installed as a PWA.',
      shareIntentTitle: 'Shared content received',
      shareIntentBody: '{title} {text}',
      install: {
        title: 'Install Comma',
        message: 'Add Comma to your home screen for a faster, premium experience and easy access to your earnings.',
        confirm: 'Install now',
        later: 'Maybe later',
      },
    },
    zones: {
      sectionTitle: 'Zone management',
      sectionLead: 'Rename, merge, or remove zone tags across every shift in your vault.',
      emptyTitle: 'No zones tagged yet',
      emptyMessage: 'Add a zone label on a shift to start tracking by area.',
      tableHeader: {
        zone: 'Zone',
        shifts: 'Shifts',
        gross: 'Gross',
        hourly: 'Hourly',
        perKm: 'Per km',
        expenses: 'Allocated expenses',
        actions: 'Actions',
      },
      rename: 'Rename',
      renameTitle: 'Rename zone',
      renameLabel: 'New name',
      mergeTitle: 'Merge zones',
      mergeInto: 'Merge into',
      mergeAction: 'Merge selected',
      mergeHelp: 'Select two or more rows to merge into a single zone tag.',
      delete: 'Clear tag',
      deleteConfirmTitle: 'Clear zone tag?',
      deleteConfirmMessage: 'Shifts will keep their data; only the {zone} tag is removed.',
      renamedToast: 'Renamed {count} shifts.',
      mergedToast: 'Merged {count} shifts.',
      clearedToast: 'Cleared tag from {count} shifts.',
      unallocated: 'Unallocated (no shift that day)',
    },
    changelog: {
      title: "What's New",
      subtitle: "Securely backup your vault to your own Google Drive.",
    },
    reports: {
      title: 'Reports',
      subtitle: 'Period summaries and export tools.',
      periodTitle: 'Select Report Period',
      templateBuilder: 'Report Template Builder',
      reportCard: 'Report Card',
      weekly: 'Weekly',
      monthly: 'Monthly',
      annual: 'Annual',
      platform: 'Per platform',
      custom: 'Custom range',
      export: 'Export',
      csv: 'CSV',
      json: 'JSON',
      print: 'Print view',
      yearInReview: 'Year in review',
    },
    schedule: {
      title: 'Schedule',
      subtitle: 'Planning and calendar',
      weekView: 'Week',
      monthView: 'Month',
      timeBlock: 'Time block',
      planningMode: 'Planning mode',
    },
    search: {
      title: 'Search',
      placeholder: 'Search shifts and expenses',
      filter: 'Filters',
      noResults: 'No matches',
    },
    modules: {
      onboarding: {
        title: 'Onboarding module',
        body: 'Orchestrator copy ships with Phase 2 (`modules/onboarding/`).',
      },
      platforms: {
        title: 'Platforms module',
        body: 'Switcher and per-platform config ship with Phase 2 (`modules/platforms/`).',
      },
      shifts: {
        title: 'Shifts module',
        body: 'CRUD, timer, and forms ship with Phase 2 (`modules/shifts/`).',
      },
      expenses: {
        title: 'Expenses module',
        body: 'Categories and recurring rules ship with Phase 2 (`modules/expenses/`).',
      },
      analytics: {
        title: 'Analytics module',
        body: 'Aggregations and chart views ship with Phase 2 (`modules/analytics/`).',
      },
      tax: {
        title: 'Tax module',
        body: 'Regional worksheets ship with Phase 2 (`modules/tax/`).',
      },
      vehicles: {
        title: 'Vehicles module',
        body: 'Garage and cost models ship with Phase 2 (`modules/vehicles/`).',
      },
      goals: {
        title: 'Goals module',
        body: 'Badges, XP, and streaks ship with Phase 2 (`modules/goals/`).',
      },
      reports: {
        title: 'Reports module',
        body: 'CSV/JSON/print/QR exports ship with Phase 2 (`modules/reports/`).',
      },
      search: {
        title: 'Search module',
        body: 'Fuse.js integration ships with Phase 2 (`modules/search/`).',
      },
      notifications: {
        title: 'Notifications module',
        body: 'All notification types ship with Phase 2 (`modules/notifications/`).',
      },
      schedule: {
        title: 'Schedule module',
        body: 'Calendar and planning ship with Phase 2 (`modules/schedule/`).',
      },
      settings: {
        title: 'Settings module',
        body: 'Full preferences UI ships with Phase 2 (`modules/settings/`).',
      },
    },
    views: {
      dashboard: {
        title: 'Dashboard',
        greeting: 'Here is your snapshot',
        placeholderBody: 'Dashboard widgets and copy finalize in Phase 2 (`views/dashboard.js`).',
        sectionAnalytics: 'Analytics',
        sectionActivity: 'Activity',
        recentEmpty: 'No recent shifts yet.',
        topShiftsEmpty: 'No shift data yet.',
        financial: {
          title: 'Financial Overview',
          subtitle: 'Track your delivery performance and earnings.',
          weeklyLog: 'Weekly Log',
          expensesNav: 'Expenses',
          export: 'Export',
          dateRange: 'DATE RANGE',
          startDate: 'Start date',
          endDate: 'End date',
          presetsAria: 'Quick range',
          presetDay: 'Day',
          presetWeek: 'Week',
          presetMonth: 'Month',
          presetQ1: 'Q1',
          presetQ2: 'Q2',
          presetQ3: 'Q3',
          presetQ4: 'Q4',
          presetQuarter: 'Quarter',
          presetYear: 'Year',
          presetYtd: 'YTD',
          presetAll: 'All',
          presetCustom: 'Custom',
          apply: 'Apply',
          totalEarnings: 'TOTAL EARNINGS',
          netIncome: 'NET INCOME',
          avgRateHr: 'AVG RATE / HR',
          totalHours: 'TOTAL HOURS',
          hoursSuffix: 'hrs',
          deliveries: 'Deliveries',
          perDelivery: '$ / Delivery',
          tipsTotal: 'Tips Total',
          expensesMetric: 'Expenses',
          outOfPocket: 'Out of Pocket',
          effectivePerHr: 'Effective $ / Hr',
          bestPerformance: 'BEST PERFORMANCE',
          needsImprovement: 'NEEDS IMPROVEMENT',
          netProfit: 'Net Profit',
          weekN: 'Week {n}',
          bestHint: 'Highest earnings recorded.',
          worstHint: 'Lower earnings.',
          noWeekData: '—',
          monthlyBreakdownTitle: 'Monthly Breakdown',
          monthlyBtnWeekly: 'Weekly',
          monthlyBtnExpenses: 'Expenses',
          monthlyBtnSummary: 'Summary',
          monthlyColPeriod: 'Period',
          monthlyColEarnings: 'Earnings',
          monthlyColExpenses: 'Expenses',
          monthlyColOop: 'Out of pocket',
          monthlyColNet: 'Net',
          monthlyColHours: 'Hours',
          monthlyColEfficiency: 'Efficiency',
          monthlyFootYtdEarnings: 'YTD earnings',
          monthlyFootYtdExpenses: 'YTD expenses',
          monthlyFootOop: 'Out of pocket',
          monthlyFootYtdNet: 'YTD net',
          monthlyFootAvgPerHr: 'Avg $/hr',
          monthlyFootEffectivePerHr: 'Effective $/hr',
          monthlyEmpty: 'No months in this range.',
          monthlyPagePrev: 'Previous',
          monthlyPageNext: 'Next',
          monthlyPageStatus: 'Page {current} of {total}',
          monthlyPagerAria: 'Monthly breakdown table pages',
          kpiGross: 'Gross Earnings',
          kpiExpenses: 'Business Expenses',
          kpiTax: 'Tax Set Aside',
          kpiNet: 'Net After Tax',
          sections: {
            insights: 'Further Analysis',
          },
        },
      },
      shifts: {
        title: 'Shifts',
        subtitle: 'Log shifts, start timers, and import history',
        placeholderBody: 'Shift list and filters finalize in Phase 2 (`views/shifts-view.js`).',
      },
      analytics: {
        title: 'Analytics',
        subtitle: 'Explore insights and customize your dashboard',
        onDashboard: 'Active on Dashboard',
        performanceModules: 'Performance Module',
        deepInsights: 'Deep Insights',
        statModules: 'Summary Stats',
        addedToDashboard: 'Widget added to dashboard',
      },
      tax: {
        title: 'Tax',
        placeholderBody: 'Tax view copy finalizes in Phase 2 (`views/tax-view.js`).',
      },
      vehicles: {
        title: 'Vehicles',
        placeholderBody: 'Vehicles view copy finalizes in Phase 2 (`views/vehicles-view.js`).',
      },
      schedule: {
        title: 'Schedule',
        placeholderBody: 'Schedule view copy finalizes in Phase 2 (`views/schedule-view.js`).',
      },
      goals: {
        title: 'Goals',
        placeholderBody: 'Goals view copy finalizes in Phase 2 (`views/goals-view.js`).',
      },
      reports: {
        title: 'Reports',
        placeholderBody: 'Reports view copy finalizes in Phase 2 (`views/reports-view.js`).',
      },
      settings: {
        title: 'Settings',
        placeholderBody: 'Settings view copy finalizes in Phase 2 (`views/settings-view.js`).',
      },
      onboarding: {
        title: 'Set up COMMA',
        placeholderBody: 'Guided setup: platforms, profile, and preferences before you enter your vault.',
      },
      about: {
        title: 'About COMMA',
        placeholderBody:
          'Data stays on your device. Full portability story and export links finalize in Phase 2.',
      },
      print: {
        title: 'Print',
        placeholderBody: 'Print-friendly earnings layouts ship with Phase 2 (`modules/reports/`).',
      },
      search: {
        title: 'Search',
        placeholderBody: 'Fuzzy search across shifts and expenses ships in Phase 2 (`modules/search/`).',
      },
    },
    ui: {
      modal: {
        close: 'Close',
      },
      confirm: {
        title: 'Are you sure?',
        destructive: 'This action is hard to undo.',
        typeToConfirm: 'Type {value} to confirm',
      },
      toast: {
        success: 'Saved',
        error: 'Error',
        warning: 'Warning',
        info: 'Info',
        celebration: 'Celebration',
        dismiss: 'Dismiss',
      },
      fab: {
        addShift: 'Quick add shift',
        addExpense: 'Add expense',
        addGoals: 'Goals',
        addSchedule: 'Add to schedule',
        endShift: 'End shift',
        openQuickActions: 'Quick actions',
        quickActionsMenu: 'Quick actions menu',
      },
      drawer: {
        close: 'Close',
      },
      progressRing: {
        label: 'Progress',
      },
      skeleton: {
        loading: 'Loading',
      },
      emptyState: {
        defaultTitle: 'Nothing here yet',
        defaultMessage: 'Try adding an item or changing filters.',
      },
      keypad: {
        title: 'Enter amount',
        confirm: 'Done',
        clear: 'Clear',
        backspace: 'Backspace',
        open: 'Keypad',
      },
    },
  },
  fr: {
    app: {
      name: 'COMMA',
      tagline: 'Gains de gig, local d’abord',
      updateAvailable: 'Mise à jour disponible — rechargez pour la dernière version',
      reload: 'Recharger',
      offlineBanner: 'Vous êtes hors ligne. Les changements se synchronisent à la reconnexion.',
      online: 'En ligne',
      offline: 'Hors ligne',
      navDashboard: 'Tableau de bord',
      navShifts: 'Quarts',
      navAnalytics: 'Analytique',
      navExpenses: 'Dépenses',
      navGoals: 'Objectifs',
      navSettings: 'Paramètres',
      navTax: 'Impôts',
      navVehicles: 'Véhicules',
      navSchedule: 'Horaire',
      navReports: 'Rapports',
      navImport: 'Importations',
      navSearch: 'Recherche',
      navMore: 'Plus',
      platformAll: 'Tout',
      headerAria: 'En-tête de l’app',
      navAria: 'Navigation principale',
      skipToContent: 'Passer au contenu principal',
      demoModeBanner:
        'Mode démo — quarts et dépenses fictifs pour 2025 (trois plateformes), pas vos vraies données.',
      exitDemo: 'Quitter la démo',
      exitDemoToast:
        'Coffre effacé — rechargement pour recommencer la configuration de COMMA depuis le début.',
    },
    common: {
      save: 'Enregistrer',
      cancel: 'Annuler',
      close: 'Fermer',
      confirm: 'Confirmer',
      all: 'Tout',
      sort: 'Trier',
      delete: 'Supprimer',
      edit: 'Modifier',
      done: 'Terminé',
      back: 'Retour',
      next: 'Suivant',
      loading: 'Chargement…',
      optional: 'Facultatif',
      required: 'Obligatoire',
      yes: 'Oui',
      no: 'Non',
      copy: 'Copier',
      share: 'Partager',
      retry: 'Réessayer',
      warning: 'Avertissement',
      ok: 'OK',
    },
    provinces: {
      on: 'Ontario',
      us: { state: 'État' },
    },
    onboarding: {
      title: 'Bienvenue sur COMMA',
      subtitle: 'Suivez vos gains dans une seule app',
      continue: 'Continuer',
      skip: 'Passer pour l’instant',
      finish: 'Commencer',
      stepProgress: 'Étape {current} sur {total}',
      welcomeTitle: 'Bienvenue',
      platformsTitle: 'Quelles plateformes utilisez-vous ?',
      vehicleTitle: 'Votre véhicule',
      goalsTitle: 'Objectif hebdomadaire',
      notificationsTitle: 'Restez sur la bonne voie',
      privacyTitle: 'Confidentialité',
      summaryTitle: 'Tout est prêt',
      placeholderBody:
        'Le texte détaillé de l’accueil arrive en phase 2 (orchestrateur + steps.js). Les clés restent stables pour `t()`.',
      tryDemo: 'Essayer la démo',
      landing: {
        kicker: 'Revenus de gig locaux',
        heroTitle: 'Vos données de gig, privées par conception.',
        heroLead:
          'COMMA est un suivi des revenus et des dépenses de gig respectueux de la vie privée pour les chauffeurs multi-applications. Enregistrez vos shifts en toute sécurité, suivez votre semaine et obtenez des aperçus prêts pour les impôts — le tout stocké localement sur votre appareil.',
        startCta: 'Commencer l\'intégration',
        restoreLink: 'Restaurer un coffre existant',
        privacyLink: 'Politique de confidentialité',
        screenshotsTitle: 'Voir quelques aperçus ci-dessous',
        sectionTitle: 'Ce que COMMA vous apporte',
        featVaultTitle: 'Coffre privé',
        featVaultBody:
          'Aucun compte requis. Vos données restent sur votre appareil, et vous pouvez les sauvegarder en toute sécurité sur votre propre Google Drive quand vous le souhaitez.',
        featShiftsTitle: 'Fil des quarts',
        featShiftsBody:
          'Plateformes, heures, distance, pourboires et primes au même endroit pour ne rien oublier.',
        featTaxTitle: 'Vision « impôts »',
        featTaxBody:
          'Un pourcentage de retenue à respecter et des indications de net pour éviter les mauvaises surprises.',
        featGoalsTitle: 'Objectifs et régularité',
        featGoalsBody:
          'Cibles hebdomadaires, séries et graphiques simples pour tenir le rythme sans tableur.',
        footnote:
          'Quelques minutes pour tout régler. Envie d’un tour d’horizon ? Essayez la démo — une année d’exemple effaçable quand vous voulez.',
      },
      demoEnabled: 'Coffre démo chargé. Explorez les données de 2025.',
      resumeTitle: 'Poursuivre la configuration ?',
      resumeMessage: 'Une configuration est déjà en cours pour cette session. Reprendre ou recommencer.',
      resumeContinue: 'Continuer',
      resumeStartOver: 'Recommencer',
      completeToast: 'Votre coffre est prêt. Bienvenue !',
      exportDone: 'Fichier de configuration téléchargé.',
      resetNeedExport: 'Exportez une sauvegarde avant de réinitialiser le coffre.',
      resetTitle: 'Réinitialiser le coffre',
      resetMessage: 'Cela supprime toutes les données COMMA locales sur cet appareil.',
      resetConfirm: 'Tout effacer',
      motivation: {
        high: 'Objectif ambitieux — on vous encourage chaque semaine.',
        mid: 'Bon équilibre entre défi et réalisme.',
        low: 'Progression douce — vous pourrez augmenter l’objectif plus tard.',
        start: 'Chaque parcours commence par un quart enregistré.',
      },
      schedule: {
        flexible: 'Horaire flexible',
        weekdays: 'Surtout en semaine',
        evenings: 'Soirées',
        weekends: 'Week-ends',
      },
      theme: { light: 'Clair', dark: 'Sombre', auto: 'Auto' },
      vehicleTypes: {
        gas: 'Essence',
        hybrid: 'Hybride',
        ev: 'Électrique',
        motorcycle: 'Moto',
        bicycle: 'Vélo',
        ebike: 'Vélo électrique',
        scooter: 'Trottinette',
        walking: 'À pied',
      },
      steps: {
        platformsTitle: 'Quelles plateformes utilisez-vous ?',
        platformsLead:
          'Sélectionnez chaque appli de gig ou de livraison avec laquelle vous gagnez de l’argent, y compris à pied ou à vélo. Modifiable à tout moment dans Paramètres.',
        platformsLeadFiltered: 'Seules les plateformes disponibles pour votre région sont affichées (registre des provinces).',
        noPlatformsForRegion: 'Aucune plateforme n’est enregistrée pour cette région. Essayez une autre région ou contactez le support.',
        profileTitle: 'Comment vous saluer ?',
        profileLead: 'Ce nom apparaît sur le tableau de bord et les exports.',
        driverName: 'Votre nom',
        avatarPick: 'Avatar',
        avatarInitials: 'Initiales',
        avatarCustom: 'Téléverser une photo',
        avatarUpload: 'Choisir une image',
        regionTitle: 'Pays ou région',
        regionLead: 'Devise, distance et repères fiscaux en découlent.',
        chooseCountryTitle: 'Dans quel pays conduisez-vous ?',
        chooseCountryLead: 'La devise et les unités de distance suivent votre marché.',
        chooseRegionTitle: 'Province, état ou région',
        chooseRegionLead: 'Les préréglages fiscaux et le catalogue s’appuient là-dessus lorsque le pays est pris en charge.',
        regionShortLabel: 'Région',
        regionOptionalLead: 'Facultatif — un court code suffit si vous voulez l’afficher sur les exports.',
        ontarioTitle: 'Ontario (Canada)',
        ontarioLead: 'COMMA v3 cible d’abord les livreurs en Ontario — CAD, kilomètres et repères fiscaux provinciaux.',
        country: 'Pays',
        countryCA: 'Canada',
        countryUS: 'États-Unis',
        countryUK: 'Royaume-Uni',
        currencyHint: 'Devise',
        vehicleTitle: 'Véhicule principal',
        vehicleLead: 'Le type aide à estimer les coûts plus tard.',
        vehicleNickname: 'Surnom',
        vehicleType: 'Type de véhicule',
        make: 'Marque',
        model: 'Modèle',
        year: 'Année',
        secondVehicleTitle: 'Un deuxième véhicule ?',
        secondVehicleLead: 'Facultatif — utile si vous alternez auto et vélo.',
        addAnotherVehicle: 'Ajouter un deuxième véhicule',
        homeBaseTitle: 'Zone de départ',
        homeBaseLead: 'Court libellé pour la zone où vous commencez souvent.',
        homeBaseLabel: 'Libellé de zone',
        homeBasePlaceholder: 'ex. Centre-ville',
        scheduleTitle: 'Horaire typique',
        scheduleLead: 'Aide pour les rappels et la planification.',
        weeklyGoalTitle: 'Objectif hebdomadaire (brut)',
        weeklyGoalLead: 'Utilisé pour l’anneau d’objectif et les rappels.',
        weeklyGoalLabel: 'Cible hebdomadaire (brut)',
        longTermGoalsTitle: 'Objectifs mensuel et annuel',
        longTermGoalsLead: 'Préremplis à partir de l’hebdomadaire — ajustez librement.',
        monthlyGoal: 'Cible mensuelle',
        annualGoal: 'Cible annuelle',
        taxTitle: 'Mise de côté fiscale',
        taxLead: 'Pourcentage approximatif à mettre de côté sur le brut.',
        province: 'Province ou territoire',
        state: 'État',
        taxRegionPlaceholder: 'Choisir…',
        taxWithholding: 'Pourcentage de retenue',
        applyPreset: 'Appliquer le préréglage régional',
        hstTitle: 'TPS / TVH',
        hstLead: 'Canada seulement — pour les feuilles TPS/TVH.',
        hstToggle: 'Je perçois ou remets la TPS / TVH',
        hstSkip: 'La TPS / TVH ne s’applique pas au pays choisi.',
        distanceTitle: 'Unités de distance',
        distanceLead: 'Affichées sur les quarts et le kilométrage.',
        unitKm: 'Kilomètres',
        unitMi: 'Miles',
        themeTitle: 'Apparence',
        themeLead: 'Modifiable à tout moment dans Paramètres.',
        notifyTitle: 'Notifications',
        notifyLead: 'Tout reste local — rien n’est téléversé.',
        completeTitle: 'Votre coffre est prêt, {name}',
        completeFallbackName: 'conducteur',
        completeLead: 'Exportez une petite configuration, chargez des exemples ou entrez directement.',
        enterVault: 'Entrer dans mon coffre',
        exportSetup: 'Enregistrer la configuration',
      },
      why: {
        platformsSummary: 'Pourquoi on demande',
        platformsBody:
          'Nous nous appuyons sur vos choix pour aligner libellés, couleurs et filtres sur les services que vous utilisez vraiment.',
        profileSummary: 'Pourquoi on demande',
        profileBody: 'Les exports sont plus clairs avec votre nom et un avatar.',
        regionSummary: 'Pourquoi on demande',
        regionBody: 'La devise et les règles de distance suivent votre pays.',
        vehicleSummary: 'Pourquoi on demande',
        vehicleBody: 'Le type de véhicule débloque les bons champs de coût.',
        secondVehicleSummary: 'Pourquoi on demande',
        secondVehicleBody: 'Deux profils gardent le kilométrage honnête si vous alternez.',
        homeBaseSummary: 'Pourquoi on demande',
        homeBaseBody: 'Les zones aident à repérer où vous gagnez le plus.',
        scheduleSummary: 'Pourquoi on demande',
        scheduleBody: 'Les rappels s’alignent sur vos plages habituelles.',
        weeklyGoalSummary: 'Pourquoi on demande',
        weeklyGoalBody: 'Une cible visible sans jugement.',
        longTermGoalsSummary: 'Pourquoi on demande',
        longTermGoalsBody: 'Les horizons lissent les semaines lentes ou chargées.',
        taxSummary: 'Pourquoi on demande',
        taxBody: 'Indicatif seulement — pas un conseil fiscal.',
        hstSummary: 'Pourquoi on demande',
        hstBody: 'Les obligations TPS/TVH diffèrent selon l’enregistrement.',
        distanceSummary: 'Pourquoi on demande',
        distanceBody: 'Une unité cohérente pour tous les quarts.',
        themeSummary: 'Pourquoi on demande',
        themeBody: 'Un bon contraste pour saisir la nuit.',
        notifySummary: 'Pourquoi on demande',
        notifyBody: 'Vous gardez le contrôle — tout tourne localement.',
      },
      notify: {
        shiftReminders: 'Rappels de quart',
        goalAlerts: 'Nudges d’objectif',
        taxReminders: 'Rappels d’échéances fiscales',
        weeklyDigest: 'Résumé hebdomadaire (brouillon local)',
      },
      validation: {
        platforms: 'Choisissez au moins une plateforme.',
        platformsNone: 'Aucune plateforme du catalogue n’est disponible pour cette région.',
        name: 'Entrez votre nom.',
        country: 'Choisissez un pays.',
        region: 'Choisissez une province, un état ou une région.',
        vehicle: 'Ajoutez un surnom et un type de véhicule.',
        secondVehicle: 'Remplissez le 2e véhicule ou décochez l’option.',
        tax: 'Indiquez un pourcentage entre 0 et 80.',
      },
      sample: {
        load: 'Charger une année démo 2025 (quarts + dépenses, trois plateformes)',
        loaded: 'Données démo 2025 ajoutées — quarts fictifs ; dépenses repérées dans les notes.',
      },
    },
    shifts: {
      addShift: 'Ajouter un quart',
      editShift: 'Modifier le quart',
      deleteShift: 'Supprimer le quart',
      duplicateShift: 'Dupliquer le quart',
      endShift: 'Terminer le quart',
      startShift: 'Commencer le quart',
      shiftTimer: 'Chronomètre de quart',
      savedToast: 'Quart enregistré',
      deletedToast: 'Quart déplacé à la corbeille',
      restoredToast: 'Quart restauré',
      undo: 'Annuler',
      timerStarted: 'Chronomètre démarré',
      timerNotRunning: 'Aucun chronomètre en cours',
      template: 'Modèle',
      templates: 'Modèles',
      noTemplates: 'Aucun modèle pour le moment.',
      saveAsTemplate: 'Enregistrer comme modèle',
      templateName: 'Nom du modèle',
      templateNamePlaceholder: 'ex. Rush du soir',
      purgeTrash: 'Vider la corbeille',
      purgedToast: 'Corbeille vidée',
      trash: 'Corbeille',
      noTrash: 'La corbeille est vide.',
      restore: 'Restaurer',
      bulkImport: 'Import groupé',
      importLead: 'Téléversez un CSV pour importer des quarts. L’aperçu montre les 5 premières lignes.',
      importPreview: 'Aperçu (5 premières lignes)',
      importAppend: 'Ajouter',
      importReplace: 'Tout remplacer',
      importParseError: 'Impossible de lire le CSV.',
      importValidationFailed: 'Échec de la validation du CSV',
      importDone: '{count} quarts importés.',
      notes: 'Notes',
      notesPlaceholder: 'Notes facultatives…',
      gross: 'Brut',
      net: 'Net',
      expenses: 'Dépenses',
      duration: 'Durée',
      orders: 'COMMAndes',
      tips: 'Pourboires',
      bonus: 'Prime',
      distance: 'Distance',
      unitKm: 'km',
      unitMiles: 'milles',
      date: 'Date',
      startTime: 'Heure de début',
      endTime: 'Heure de fin',
      advancedToggle: 'Basique / Avancé',
      onlineMinutes: 'Minutes en ligne',
      activeMinutes: 'Minutes actives',
      vehicle: 'Véhicule',
      vehicleNone: 'Aucun véhicule',
      vehicleEstimate: 'Estimation véhicule',
      weather: 'Météo',
      weatherClear: 'Clair',
      weatherRain: 'Pluie',
      weatherSnow: 'Neige',
      weatherFog: 'Brouillard',
      weatherHeat: 'Chaleur',
      zone: 'Zone',
      zonePlaceholder: 'ex. Centre-ville',
      mood: 'Humeur',
      platform: 'Plateforme',
      platformExtras: 'Détails plateforme',
      psObjectHint: 'Objet JSON — JSON invalide conserve la valeur précédente.',
      psCOMMAPlaceholder: 'Valeurs séparées par des virgules',
      ps: {
        peakPay: 'Peak pay',
        dashZone: 'Zone Dash',
        acceptanceRate: 'Taux d’acceptation (%)',
        customerRating: 'Note clients',
        surgeMultiplier: 'Multiplicateur surge',
        proStatus: 'Statut Pro',
        completionRate: 'Taux de complétion (%)',
        questOnlineMinutes: 'Minutes en ligne (quête)',
        orderTypeSplit: 'Répartition types de commande (JSON)',
        attendanceScore: 'Score de présence',
        creditsPromos: 'Crédits / promos',
        cityScore: 'Score ville',
        batchCount: 'Nombre de lots',
        batchTypes: 'Types de lots (séparés par des virgules)',
        blockDurationMinutes: 'Durée du bloc (minutes)',
        blockType: 'Type de bloc',
      },
      emptyTitle: 'Aucun quart',
      emptyMessage: 'Enregistrez votre premier quart pour voir les tendances.',
      deleteConfirm: 'Supprimer ce quart ? Cette action est irréversible.',
      filterPresetsAria: 'Filtres de dates rapides',
      presetWeek: 'Semaine',
      presetYtd: 'Depuis janv.',
      presetAll: 'Tout',
      rangeStart: 'Début de plage',
      rangeEnd: 'Fin de plage',
      rangeLabel: 'Plage de dates',
      headerToolsAria: 'Outils — quarts',
      rangeApply: 'Appliquer',
      sortByDate: 'Tri',
      sortNewest: 'Plus récent',
      sortOldest: 'Plus ancien',
      pagePrev: 'Précédent',
      pageNext: 'Suivant',
      pageStatus: 'Page {current} sur {total}',
      pagerAria: 'Pagination de la liste des quarts',
      entryScopeLabel: 'Type de saisie',
      entryOneDay: 'Un jour',
      entryWeekDays: 'Plusieurs jours',
      weekContaining: 'Semaine contenant',
      weekDaysHint: 'Jours à inclure à l’enregistrement',
      weekSaveHint: 'Les mêmes détails sont enregistrés pour chaque jour coché (pratique pour une semaine type). Les jours en conflit avec un quart existant peuvent être ignorés.',
      weekNoDays: 'Cochez au moins un jour.',
      savedManyToast: '{count} quarts enregistrés',
      weekPartialToast: '{ok} quarts enregistrés ; {skip} ignorés.',
      emptyFilteredTitle: 'Aucun quart dans cette plage',
      emptyFilteredMessage: 'Élargissez les dates ou changez les filtres.',
    },
    analytics: {
      title: 'Analytique',
      subtitle: 'Gains, rythme et habitudes',
      hourlyRate: 'Taux horaire',
      netHourly: 'Taux horaire net',
      earnings: 'Gains',
      distance: 'Distance',
      tips: 'Pourboires',
      bonus: 'Prime',
      orders: 'COMMAndes',
      zones: 'Zones',
      trends: 'Tendances',
      heatmap: 'Carte de chaleur',
      scatter: 'Nuage de points',
      byDayOfWeek: 'Par jour de la semaine',
      byHour: 'Par heure',
      utilization: 'Utilisation',
      records: 'Records personnels',
      projection: 'Projection hebdomadaire',
      streak: 'Série',
      compare: 'Comparer les périodes',
      recentActivity: 'Activité récente',
      topShifts: 'Meilleurs quarts',
      zeroDays: 'Jours sans quart',
      bestWindow: 'Meilleures plages',
      bestDay: 'Meilleur jour',
      bestHour: 'Meilleure heure',
      bestZone: 'Meilleure zone',
      lastPeriod: 'Semaine précédente',
      thisPeriod: 'Cette semaine',
      baseIncome: 'Base',
      earningsVsHours: 'Gains vs heures',
      emptyTitle: 'Pas assez de données',
      emptyMessage: 'Ajoutez quelques quarts pour débloquer graphiques et analyses.',
    },
    notifications: {
      title: 'Notifications',
      permissionDenied: 'Les notifications sont bloquées dans ce navigateur.',
      enableHint: 'Activez les notifications pour les rappels de quart.',
      reminderShift: 'Rappel de quart',
      goalMet: 'Objectif atteint',
      taxDeadline: 'Échéance fiscale proche',
      weeklySummary: 'Résumé hebdomadaire',
      openSettings: 'Ouvrir les paramètres',
    },
    errors: {
      generic: 'Une erreur s’est produite. Réessayez.',
      offline: 'Vous semblez hors ligne.',
      network: 'La requête réseau a échoué. Vérifiez la connexion.',
      dbOpen: 'Impossible d’ouvrir la base locale.',
      dbMigration: 'La mise à niveau de la base a échoué.',
      invalidInput: 'Vérifiez les champs et réessayez.',
      notFound: 'Élément introuvable.',
      permission: 'Permission refusée.',
      importFailed: 'Import impossible. Vérifiez le format du fichier.',
      exportFailed: 'Export impossible. Réessayez.',
      viewRender: 'Cet écran n’a pas pu être chargé.',
      storeBindMissing: 'Liaison d’état : élément introuvable.',
    },
    vehicles: {
      title: 'Véhicules',
      add: 'Ajouter un véhicule',
      edit: 'Modifier le véhicule',
      fuel: 'Carburant',
      ev: 'Électrique',
      maintenance: 'Entretien',
      mileage: 'Kilométrage',
      depreciation: 'Amortissement',
      efficiency: 'Rendement',
    },
    expenses: {
      title: 'Dépenses',
      add: 'Ajouter une dépense',
      editTitle: 'Modifier la dépense',
      subtitle: 'Suivez carburant, entretien et coûts professionnels',
      category: 'Catégorie',
      categories: {
        fuel: 'Carburant',
        maintenance: 'Entretien',
        parking: 'Stationnement',
        tolls: 'Péages',
        insurance: 'Assurance',
        registration: 'Immatriculation',
        phone: 'Téléphone',
        data_plan: 'Forfait données',
        car_wash: 'Lavage auto',
        supplies: 'Fournitures',
        meals: 'Repas',
        bank_fees: 'Frais bancaires',
        software: 'Logiciels',
        accounting: 'Comptabilité',
        other: 'Autre',
      },
      cat: {
        fuel: 'Carburant',
        maintenance: 'Entretien',
        parking: 'Stationnement',
        tolls: 'Péages',
        insurance: 'Assurance',
        registration: 'Immatriculation',
        phone: 'Téléphone',
        data_plan: 'Forfait données',
        car_wash: 'Lavage auto',
        supplies: 'Fournitures',
        meals: 'Repas',
        bank_fees: 'Frais bancaires',
        software: 'Logiciels',
        accounting: 'Comptabilité',
        bike_maintenance: 'Entretien vélo / vélo électrique',
        other: 'Autre',
      },
      uncategorized: 'Sans catégorie',
      amount: 'Montant',
      date: 'Date',
      platformAssignment: 'Plateforme',
      businessUsePct: 'Usage professionnel %',
      businessUseLabel: '{pct}% utilisé pour les livraisons',
      notes: 'Notes',
      notesPlaceholder: 'Note facultative…',
      receipt: 'Reçu',
      receiptHint: 'Téléversez une photo de reçu (stockée localement).',
      receiptAttached: 'Reçu joint.',
      recurring: 'Récurrent',
      recurringInterval: 'Fréquence',
      recurringWeekly: 'Hebdomadaire',
      recurringMonthly: 'Mensuel',
      recurringAnnual: 'Annuel',
      hstItc: 'Montant TPS/TVH / CTI',
      confirmedPaid: 'J’ai déjà payé cette dépense récurrente',
      savedToast: 'Dépense enregistrée',
      deletedToast: 'Dépense supprimée',
      autoExpenseTitle: 'Dépense carburant (quart)',
      autoExpenseTitleEv: 'Dépense recharge (quart)',
      autoExpenseNote: 'Suggestion depuis le quart no {shiftId}',
      confirmAutoExpense: 'Enregistrer la dépense',
      fuelExpenseToast: 'Carburant estimé pour ce quart : {amount}.',
      fuelExpenseToastEv: 'Coût de recharge estimé pour ce quart : {amount}.',
      addExpenseToastAction: 'Ajouter la dépense',
      tabAll: 'Toutes',
      tabByCategory: 'Par catégorie',
      tabRecurring: 'Récurrentes',
      tabDeductions: 'Déductions',
      byCategoryHint: 'Les totaux utilisent les mêmes filtres que l’onglet Toutes (part professionnelle).',
      categoryTotalHeader: 'Total',
      recurringPanelHint: 'Modèles récurrents et prochaine échéance.',
      recurringNextDue: 'Prochaine échéance',
      recurringAmount: 'Montant',
      recurringEditTitle: 'Enregistrer ce paiement',
      recurringPromptTitle: 'Dépense récurrente à échéance',
      recurringPromptBody: '{category} — {amount} — échéance {date}. L’avez-vous payée ?',
      recurringYesPaid: 'Oui, payée',
      recurringEditAmount: 'Modifier le montant',
      recurringSkip: 'Plus tard',
      deductionsTitle: 'Déductions et fiscalité',
      deductionsLead: 'Le pourcentage professionnel et les déductions fiscales se gèrent dans Impôts.',
      deductionsGoTax: 'Ouvrir Impôts',
      filterStartDate: 'Date de début',
      filterEndDate: 'Date de fin',
      minAmount: 'Montant min',
      maxAmount: 'Montant max',
      receiptOnly: 'Avec reçu',
      sortDateDesc: 'Date (récentes)',
      sortDateAsc: 'Date (anciennes)',
      sortAmountDesc: 'Montant (décroissant)',
      sortAmountAsc: 'Montant (croissant)',
      sortCategory: 'Catégorie (A-Z)',
      sortPlatform: 'Plateforme (A-Z)',
      emptyTitle: 'Aucune dépense',
      emptyMessage: 'Suivez carburant, entretien et autres coûts ici.',
      addNewExpense: 'Nouvelle dépense',
      recordsTitle: 'Historique des dépenses',
      searchPlaceholder: 'Rechercher…',
      rowsPerPage: 'Lignes par page',
      rowsOption: '{n} lignes',
      resetFilters: 'Réinitialiser',
      moreFilters: 'Filtres avancés',
      kpiTotal: 'Total des dépenses',
      kpiCount: 'Nombre',
      kpiAverage: 'Moyenne par dépense',
      kpiCategories: 'Catégories',
      chartByCategory: 'Dépenses par catégorie',
      chartMonthlyTrend: 'Tendance mensuelle',
      columnDescription: 'Description',
      columnActions: 'Actions',
      sortAria: 'Trier par {column}',
      totalsLabel: 'Totaux',
      totalsExpensesCount: '{n} dépenses',
      pageInfo: 'Page {page} / {pages} ({total} lignes)',
      previousPage: 'Précédent',
      nextPage: 'Suivant',
    },
    platforms: {
      title: 'Plateformes',
      switcher: 'Filtre plateforme',
      add: 'Ajouter une plateforme',
      config: 'Paramètres de plateforme',
      terminology: 'Terminologie',
      settingsSectionTitle: 'Plateformes',
      settingsSectionLead: 'Gérez les apps actives, les objectifs par plateforme et le sélecteur d’en-tête.',
      switcherMode: 'Style du sélecteur (en-tête)',
      switcherTabs: 'Onglets',
      switcherDropdown: 'Menu déroulant',
      switcherTabsCompactHint:
        'Les onglets restent sur une ligne (défilement horizontal si besoin). Sur petit écran, un menu déroulant s’affiche automatiquement.',
      switcherModeSaved: 'Préférence du sélecteur enregistrée.',
      weeklyGoal: 'Objectif hebdomadaire ($)',
      monthlyGoal: 'Objectif mensuel ($)',
      taxRate: 'Taux fiscal local (%)',
      notes: 'Notes',
      helpLink: 'Centre d’aide',
      apiDisclaimer:
        'COMMA n’est relié à aucune API de plateforme. Les données saisies restent sur cet appareil.',
      deactivate: 'Désactiver',
      deactivateTitle: 'Désactiver la plateforme ?',
      deactivateMessage: 'Les quarts passés pour {name} restent dans le coffre. Vous pourrez réactiver plus tard.',
      deactivated: 'Plateforme désactivée.',
      lastActive: 'Gardez au moins une plateforme active.',
      saved: 'Paramètres enregistrés.',
      noInactive: 'Toutes les plateformes du catalogue sont déjà actives.',
      pickPlatform: 'Choisir une plateforme…',
      added: 'Plateforme ajoutée.',
      reactivate: 'Réactiver',
      reactivated: 'Plateforme réactivée.',
      inactiveHeading: 'Plateformes inactives',
      cardMeta: 'Cibles et notes par plateforme',
      otherExplain: 'Le nom et la couleur apparaissent dans le sélecteur et les rapports.',
      otherName: 'Nom affiché',
      otherColor: 'Couleur d’accent',
      activateOtherTitle: 'Configurer « Autre »',
    },
    tax: {
      title: 'Impôts',
      subtitle: 'Vue annuelle, mise de côté et aide à la déclaration',
      taxYear: 'Année fiscale',
      virtualJar: 'Suivi de mise de côté fiscale',
      targetSetAside: 'Mise de côté cible',
      currentSetAside: 'Mise de côté actuelle',
      hstCollectedTracker: 'TPS/TVH perçue',
      itcTracker: 'Crédits de taxe sur les intrants (CTI)',
      collected: 'Perçue',
      remittable: 'Montant estimé à remettre',
      incomeSnapshot: 'Aperçu du revenu',
      grossIncome: 'Revenu brut',
      businessExpenses: 'Dépenses d’entreprise',
      netIncome: 'Revenu net',
      netAfterSetAside: 'Net après mise de côté',
      provinceStatePresets: 'Préréglages de taux province/état',
      province: 'Province',
      state: 'État',
      applyPreset: 'Appliquer au profil',
      currentRate: 'Taux de retenue actuel',
      presetApplied: 'Taux fiscal mis à jour à {rate}.',
      mileageDeduction: 'Kilométrage et comparaison des coûts',
      totalDistance: 'Distance professionnelle',
      standardMileage: 'Méthode kilométrage standard',
      actualCost: 'Méthode des coûts réels',
      recommendedMethod: 'Déduction la plus élevée cette année',
      methodActual: 'Coûts réels',
      methodStandard: 'Kilométrage standard',
      kilometres: 'km',
      miles: 'mi',
      cppEstimator: 'Estimateur RPC (Canada)',
      seTaxEstimator: 'Estimateur travail autonome (É.-U.)',
      estimatedValue: 'Montant annuel estimé',
      cppNote: 'Estimation de planification seulement; validez avec les feuilles ARC.',
      seTaxNote: 'Estimation de planification seulement; validez avec les feuilles IRS.',
      installmentDeadlines: 'Échéances des acomptes',
      overdue: 'en retard',
      t2125: {
        title: 'Aide T2125 (Canada)',
        grossIncome: 'Partie 3A — Revenu brut d’entreprise',
        advertising: 'Ligne 8521 — Publicité',
        meals: 'Ligne 8523 — Repas et divertissement',
        motorVehicle: 'Ligne 9281 — Dépenses véhicule',
        supplies: 'Ligne 8811 — Fournitures et bureau',
        other: 'Partie 4 — Autres dépenses déductibles',
        netIncome: 'Partie 5 — Revenu net d’entreprise',
      },
      scheduleC: {
        title: 'Aide Schedule C (É.-U.)',
        partIIncome: 'Partie I — Revenu',
        partIIExpenses: 'Partie II — Dépenses',
        carTruck: 'Ligne 9 — Dépenses auto/camion',
        depreciation: 'Ligne 13 — Amortissement',
        homeOffice: 'Ligne 30 — Bureau à domicile',
        other: 'Partie V — Autres dépenses',
        netProfit: 'Ligne 31 — Profit ou perte net',
      },
      referenceLinks: 'Références officielles',
      links: {
        businessIncomeGuide: 'Revenus et dépenses d’entreprise',
        scheduleCGuide: 'Guide Schedule C',
        hstGuide: 'TPS/TVH pour entreprises',
        estimatedTaxes: 'Impôts estimés',
      },
      footnoteCanada: 'Ceci n’est pas un conseil fiscal. Vérifiez avec l’ARC ou un professionnel.',
      footnoteUs: 'Ceci n’est pas un conseil fiscal. Vérifiez avec l’IRS ou un professionnel.',
      footnoteGeneric: 'Ceci n’est pas un conseil fiscal. Vérifiez avec l’administration fiscale locale ou un professionnel.',
      genericEstimatorTitle: 'Cotisations et prélèvements (estimation)',
      genericEstimatorNote: 'Estimation indicative seulement; les règles varient selon le pays — vérifiez les sources officielles.',
      exportSummary: 'Exporter le résumé fiscal',
      exportHint: 'Téléchargez le résumé annuel en JSON ou CSV.',
      exportJson: 'Exporter JSON',
      exportCsv: 'Exporter CSV',
      exportedJson: 'Résumé fiscal JSON exporté.',
      exportedCsv: 'Résumé fiscal CSV exporté.',
    },
    goals: {
      title: 'Objectifs',
      weeklyTarget: 'Objectif hebdomadaire',
      badges: 'Badges',
      xp: 'XP',
      challenges: 'Défis',
      streakDays: 'Série de jours',
      level: 'Niveau',
      weeksHit: 'Semaines atteintes',
      of: 'sur',
      thermometer: 'Thermomètre',
      activeGoals: 'Objectifs actifs',
      history: 'Historique des objectifs',
      to: 'à',
      hit: 'atteint',
      inProgress: 'en cours',
    },
    settings: {
      title: 'Paramètres',
      subtitle: 'Compte, apparence et coffre',
      tabsAriaLabel: 'Sections des paramètres',
      tabYou: 'Vous',
      tabAppearance: 'Apparence',
      tabPlatforms: 'Plateformes',
      tabAlerts: 'Alertes',
      tabData: 'Données',
      tabAbout: 'À propos',
      groupProfileTitle: 'Profil',
      groupLocationTitle: 'Lieu',
      groupLocationLead: 'Pays, région, plateforme par défaut et unités de distance.',
      lookFeelSectionTitle: 'Affichage et locale',
      lookFeelSectionLead: 'Thème, typographie, accent, formats et devise.',
      accentPresetsAria: 'Couleurs d’accent prédéfinies',
      accentPresetUse: 'Utiliser la couleur d’accent',
      accentLabel: 'Couleur d’accent',
      accentCustomHex: 'Hex personnalisé',
      dashboardSectionTitle: 'Tableau de bord',
      dashboardSectionLead: 'Glisser pour réordonner les widgets. Jusqu’à 3 stats héros.',
      dataVaultSectionTitle: 'État du coffre et exports',
      platformsSectionLead: 'Activez les plateformes et ajustez les valeurs par plateforme.',
      language: 'Langue',
      dateFormat: 'Format de date',
      timeFormat: 'Format d’heure',
      theme: 'Thème',
      distanceUnit: 'Unité de distance',
      currency: 'Devise',
      notifications: 'Notifications',
      dataExport: 'Exporter les données',
      dangerZone: 'Zone sensible',
      about: 'À propos',
      shortcutsTitle: 'Raccourcis clavier',
      shortcutsLead: 'Navigation rapide et recherche (lorsque le focus n’est pas dans un champ texte).',
      dataSectionTitle: 'Données et sauvegardes',
      dataSectionLead:
        'Les exports CSV, impressions, résumés fiscaux et l’import se trouvent sous Rapports. Le bouton ci-dessous télécharge une sauvegarde JSON complète du coffre (conservez-la en lieu sûr).',
      openReportsBtn: 'Ouvrir rapports et exports',
      exportVaultBtn: 'Télécharger le coffre (JSON)',
      exportVaultToast: 'Sauvegarde téléchargée. Une date de sauvegarde a été enregistrée pour les vérifications avant réinitialisation.',
      workspaceSectionTitle: 'Aller à l’espace de travail',
      workspaceSectionLead: 'Ouvrir un écran principal depuis ici (mêmes routes que la navigation).',
      marketSectionTitle: 'Marché et distance',
      marketSectionLead:
        'Le pays et la région influencent les taxes par défaut, la devise et les unités de distance sur les cartes et le kilométrage.',
      goalsTaxSectionTitle: 'Objectifs de revenu et fiscalité',
      goalsTaxSectionLead: 'Cibles et retenue sont des estimations de planification — mêmes champs que l’intégration.',
      labelCountry: 'Pays',
      labelDistanceUnit: 'Unité de distance',
      labelPrimaryPlatform: 'Plateforme principale',
      primaryPlatformNone: 'Aucune par défaut',
      saveMarket: 'Enregistrer marché et locale',
      marketSaved: 'Marché et locale enregistrés.',
      labelWeeklyGoalDollars: 'Objectif hebdomadaire ($)',
      labelMonthlyGoalDollars: 'Objectif mensuel ($)',
      labelAnnualGoalDollars: 'Objectif annuel ($)',
      labelTaxWithhold: 'Mise de côté fiscale %',
      labelWorkSchedule: 'Horaire typique',
      saveGoalsTax: 'Enregistrer objectifs et fiscalité',
      goalsTaxSaved: 'Objectifs et fiscalité enregistrés.',
      demoBanner: 'Mode démo — les données d’exemple sont réinitialisées en quittant.',
      exitDemoBtn: 'Quitter la démo',
      quickSnapshotBtn: 'Instantané des tables',
      quickSnapshotToast: 'Instantané téléchargé et horodatage de sauvegarde enregistré.',
      dangerSectionTitle: 'Zone sensible',
      dangerSectionLead:
        'Effacer le coffre supprime quarts, dépenses et paramètres locaux après confirmation en tapant RESET. Exportez une sauvegarde d’abord.',
      dangerResetBtn: 'Effacer le coffre local…',
      aboutSectionTitle: 'À propos',
      aboutSectionLead: 'Notes produit, astuces communautaires et fonctions expérimentales.',
      aboutAppLink: 'Finitions et communauté',
      aboutRouteLink: 'Infos build / route',
      notificationsLead:
        'Les alertes passent par le bloc « Fonctions de l’appareil » sur cet onglet lorsque le navigateur le permet.',
      backupTitle: 'Sauvegarde Cloud',
      backupLead: 'Google Drive · Dossier App Data',
      backupConnectBtn: 'Connecter Google Drive',
      backupDisconnectBtn: 'Déconnecter Drive',
      backupNowBtn: 'Sauvegarder',
      backupRestoreBtn: 'Restaurer',
      backupStatusConnected: 'Connecté',
      backupStatusDisconnected: 'Drive déconnecté',
      backupStatusOffline: 'Pas de connexion internet',
      backupStatusOverdue: 'Sauvegarde en retard',
      backupStatusRecently: 'Sauvegardé récemment',
      backupStatusToday: 'Sauvegardé aujourd’hui',
      backupStatusNone: 'Aucune sauvegarde',
      backupStatusOfflineSub: 'La sauvegarde reprendra une fois en ligne.',
      backupConnectSub: 'Vos données restent sur l’appareil. Drive est optionnel.',
      backupStatusDisconnectedSub: 'Reconnectez-vous pour reprendre les sauvegardes.',
      backupSuccessToast: 'Coffre sauvegardé sur Drive ✓',
      backupFailToast: 'Échec de la sauvegarde',
      backupRestoreSuccessToast: 'Coffre restauré avec succès ✓',
      backupRestoreFailToast: 'Échec de la restauration',
      backupDemoWarning: 'C’est le mode démo. Vous ne pouvez pas connecter Drive ici. Veuillez quitter la démo et créer votre propre coffre.',
      backupRestoreTitle: 'Restaurer depuis Drive',
      backupRestoreSearching: 'Recherche de sauvegardes...',
      backupRestoreEmpty: 'Aucune sauvegarde trouvée dans Google Drive.',
      backupRestoreConfirmTitle: 'Restaurer cette sauvegarde ?',
      backupRestoreConfirmMessage: 'Ceci REMPLACERA vos données locales actuelles. Assurez-vous d’avoir un export manuel si vous voulez les conserver.',
      backupRestoreConfirmText: 'Restaurer le coffre',
      backupDisconnectConfirmTitle: 'Déconnecter Google Drive ?',
      backupDisconnectConfirmMessage: 'Les sauvegardes automatiques s’arrêteront. Vos données resteront dans Drive mais ne seront plus mises à jour.',
      shortcuts: {
        ctrlOrCmd: 'Ctrl / ⌘',
        searchCmdK: 'Ouvrir la recherche',
        searchSlash: 'Ouvrir la recherche (hors champ texte)',
        escOverlays: 'Fermer les fenêtres superposées',
      },
    },
    pwa: {
      sectionTitle: 'Fonctions de l’appareil',
      sectionLead: 'Activez des API de navigateur optionnelles. Les permissions ne sont demandées qu’à votre demande explicite.',
      capabilityHeading: 'Capacités détectées',
      supported: 'Pris en charge',
      unsupported: 'Non disponible sur ce navigateur',
      requestNotifications: 'Activer les notifications',
      notificationsGranted: 'Notifications activées',
      notificationsDenied: 'Notifications bloquées par le navigateur',
      notificationsUnsupported: 'Notifications indisponibles ici',
      testVibrate: 'Tester la vibration',
      vibrationOk: 'Une vibration rapide a été envoyée.',
      vibrationUnsupported: 'Cet appareil ne peut pas vibrer.',
      toggleFullscreen: 'Basculer le plein écran',
      fullscreenOn: 'Plein écran activé.',
      fullscreenOff: 'Plein écran désactivé.',
      fullscreenUnsupported: 'Plein écran indisponible ici.',
      backgroundSync: 'Synchronisation en arrière-plan',
      backgroundSyncOn: 'Les exports différés seront réessayés automatiquement.',
      backgroundSyncOff: 'Indisponible — les exports seront réessayés à la prochaine ouverture.',
      wakeLock: 'Verrouillage de l’écran',
      wakeLockOn: 'L’écran reste actif pendant un quart en cours.',
      wakeLockOff: 'Verrouillage d’écran indisponible.',
      fileSystem: 'Accès au système de fichiers',
      fileSystemOn: 'Choisir l’emplacement de sauvegarde des rapports.',
      fileSystemOff: 'Retombe sur le dossier de téléchargement.',
      shareTarget: 'Cible de partage',
      shareTargetOn: 'D’autres apps peuvent partager du texte vers COMMA.',
      shareTargetOff: 'La cible de partage s’active une fois installé en PWA.',
      shareIntentTitle: 'Contenu partagé reçu',
      shareIntentBody: '{title} {text}',
      install: {
        title: 'Installer Comma',
        message: 'Ajoutez Comma à votre écran d’accueil pour une expérience premium plus rapide et un accès facile à vos gains.',
        confirm: 'Installer maintenant',
        later: 'Plus tard',
      },
    },
    zones: {
      sectionTitle: 'Gestion des zones',
      sectionLead: 'Renommer, fusionner ou retirer des étiquettes de zone sur tous les quarts.',
      emptyTitle: 'Aucune zone étiquetée',
      emptyMessage: 'Ajoutez une étiquette de zone sur un quart pour commencer.',
      tableHeader: {
        zone: 'Zone',
        shifts: 'Quarts',
        gross: 'Brut',
        hourly: 'Taux/h',
        perKm: 'Par km',
        expenses: 'Dépenses imputées',
        actions: 'Actions',
      },
      rename: 'Renommer',
      renameTitle: 'Renommer la zone',
      renameLabel: 'Nouveau nom',
      mergeTitle: 'Fusionner les zones',
      mergeInto: 'Fusionner vers',
      mergeAction: 'Fusionner la sélection',
      mergeHelp: 'Sélectionnez au moins deux lignes pour les fusionner.',
      delete: 'Effacer l’étiquette',
      deleteConfirmTitle: 'Effacer l’étiquette de zone ?',
      deleteConfirmMessage: 'Les quarts conservent leurs données; seule l’étiquette {zone} est retirée.',
      renamedToast: '{count} quarts renommés.',
      mergedToast: '{count} quarts fusionnés.',
      clearedToast: 'Étiquette retirée de {count} quarts.',
      unallocated: 'Non imputé (aucun quart ce jour-là)',
    },
    reports: {
      title: 'Rapports',
      export: 'Exporter',
      csv: 'CSV',
      json: 'JSON',
      print: 'Version imprimable',
      yearInReview: 'Bilan de l’année',
    },
    schedule: {
      title: 'Horaire',
      subtitle: 'Planification et calendrier',
      weekView: 'Semaine',
      monthView: 'Mois',
      timeBlock: 'Bloc de temps',
      planningMode: 'Mode planification',
    },
    search: {
      title: 'Recherche',
      placeholder: 'Rechercher quarts et dépenses',
      filter: 'Filtres',
      noResults: 'Aucun résultat',
    },
    modules: {
      onboarding: {
        title: 'Module d’accueil',
        body: 'Texte d’orchestration en phase 2 (`modules/onboarding/`).',
      },
      platforms: {
        title: 'Module plateformes',
        body: 'Sélecteur et config par plateforme en phase 2 (`modules/platforms/`).',
      },
      shifts: {
        title: 'Module quarts',
        body: 'CRUD, chronomètre et formulaires en phase 2 (`modules/shifts/`).',
      },
      expenses: {
        title: 'Module dépenses',
        body: 'Catégories et récurrence en phase 2 (`modules/expenses/`).',
      },
      analytics: {
        title: 'Module analytique',
        body: 'Agrégations et graphiques en phase 2 (`modules/analytics/`).',
      },
      tax: {
        title: 'Module fiscal',
        body: 'Feuilles par région en phase 2 (`modules/tax/`).',
      },
      vehicles: {
        title: 'Module véhicules',
        body: 'Garage et coûts en phase 2 (`modules/vehicles/`).',
      },
      goals: {
        title: 'Module objectifs',
        body: 'Badges, XP et séries en phase 2 (`modules/goals/`).',
      },
      reports: {
        title: 'Module rapports',
        body: 'Exports CSV/JSON/impression/QR en phase 2 (`modules/reports/`).',
      },
      search: {
        title: 'Module recherche',
        body: 'Intégration Fuse.js en phase 2 (`modules/search/`).',
      },
      notifications: {
        title: 'Module notifications',
        body: 'Tous les types de notifications en phase 2 (`modules/notifications/`).',
      },
      schedule: {
        title: 'Module horaire',
        body: 'Calendrier et planification en phase 2 (`modules/schedule/`).',
      },
      settings: {
        title: 'Module paramètres',
        body: 'Préférences complètes en phase 2 (`modules/settings/`).',
      },
    },
    views: {
      dashboard: {
        title: 'Tableau de bord',
        greeting: 'Voici votre aperçu',
        placeholderBody: 'Widgets et texte du tableau de bord en phase 2 (`views/dashboard.js`).',
        sectionAnalytics: 'Analytique',
        sectionActivity: 'Activité',
        recentEmpty: 'Aucun quart récent pour le moment.',
        topShiftsEmpty: 'Aucune donnée de quart pour le moment.',
        financial: {
          title: 'Vue financière',
          subtitle: 'Suivez vos gains et la performance de vos livraisons.',
          weeklyLog: 'Journal hebdo',
          expensesNav: 'Dépenses',
          export: 'Exporter',
          dateRange: 'PÉRIODE',
          startDate: 'Date de début',
          endDate: 'Date de fin',
          presetsAria: 'Périodes rapides',
          presetDay: 'Jour',
          presetWeek: 'Semaine',
          presetMonth: 'Mois',
          presetQ1: 'T1',
          presetQ2: 'T2',
          presetQ3: 'T3',
          presetQ4: 'T4',
          presetQuarter: 'Trimestre',
          presetYear: 'Année',
          presetYtd: 'À ce jour',
          presetAll: 'Tout',
          presetCustom: 'Personnalisé',
          apply: 'Appliquer',
          totalEarnings: 'GAINS BRUTS',
          netIncome: 'REVENU NET',
          avgRateHr: 'TAUX MOY. / H',
          totalHours: 'HEURES TOTALES',
          hoursSuffix: 'h',
          deliveries: 'Livraisons',
          perDelivery: '$ / Livraison',
          tipsTotal: 'Pourboires',
          expensesMetric: 'Dépenses',
          outOfPocket: 'Sortie de poche',
          effectivePerHr: '$ eff. / h',
          bestPerformance: 'MEILLEURE PERFORMANCE',
          needsImprovement: 'À AMÉLIORER',
          netProfit: 'profit net',
          weekN: 'Semaine {n}',
          bestHint: 'Gains les plus élevés enregistrés.',
          worstHint: 'Gains plus faibles.',
          noWeekData: '—',
          monthlyBreakdownTitle: 'Répartition mensuelle',
          monthlyBtnWeekly: 'Hebdomadaire',
          monthlyBtnExpenses: 'Dépenses',
          monthlyBtnSummary: 'Synthèse',
          monthlyColPeriod: 'Période',
          monthlyColEarnings: 'Gains',
          monthlyColExpenses: 'Dépenses',
          monthlyColOop: 'Déboursés',
          monthlyColNet: 'Net',
          monthlyColHours: 'Heures',
          monthlyColEfficiency: 'Efficacité',
          monthlyFootYtdEarnings: 'Cumul gains (période)',
          monthlyFootYtdExpenses: 'Cumul dépenses',
          monthlyFootOop: 'Déboursés',
          monthlyFootYtdNet: 'Cumul net',
          monthlyFootAvgPerHr: 'Moy. $/h',
          monthlyFootEffectivePerHr: '$/h effectif',
          monthlyEmpty: 'Aucun mois dans cette plage.',
          monthlyPagePrev: 'Précédent',
          monthlyPageNext: 'Suivant',
          monthlyPageStatus: 'Page {current} sur {total}',
          monthlyPagerAria: 'Pagination du tableau mensuel',
          kpiGross: 'Gains bruts',
          kpiExpenses: 'Dépenses d’entreprise',
          kpiTax: 'Mise de côté fiscale',
          kpiNet: 'Net après impôts',
          sections: {
            insights: 'Analyses d’activité',
          },
        },
      },
      shifts: {
        title: 'Quarts',
        subtitle: 'Enregistrez vos quarts, démarrez un chronomètre et importez votre historique',
        placeholderBody: 'Liste et filtres en phase 2 (`views/shifts-view.js`).',
      },
      analytics: {
        title: 'Analytique',
        subtitle: 'Explorez vos analyses et personnalisez votre tableau de bord',
        onDashboard: 'Actif sur le tableau de bord',
        performanceModules: 'Module de performance',
        deepInsights: 'Analyses approfondies',
        statModules: 'Stats de synthèse',
        addedToDashboard: 'Widget ajouté au tableau de bord',
      },
      tax: {
        title: 'Impôts',
        placeholderBody: 'Texte de la vue fiscale en phase 2 (`views/tax-view.js`).',
      },
      vehicles: {
        title: 'Véhicules',
        placeholderBody: 'Texte de la vue véhicules en phase 2 (`views/vehicles-view.js`).',
      },
      schedule: {
        title: 'Horaire',
        placeholderBody: 'Texte de la vue horaire en phase 2 (`views/schedule-view.js`).',
      },
      goals: {
        title: 'Objectifs',
        placeholderBody: 'Texte de la vue objectifs en phase 2 (`views/goals-view.js`).',
      },
      reports: {
        title: 'Rapports',
        placeholderBody: 'Texte de la vue rapports en phase 2 (`views/reports-view.js`).',
      },
      settings: {
        title: 'Paramètres',
        placeholderBody: 'Texte de la vue paramètres en phase 2 (`views/settings-view.js`).',
      },
      onboarding: {
        title: 'Configurer COMMA',
        placeholderBody:
          'Configuration guidée : plateformes, profil et préférences avant d’entrer dans votre coffre.',
      },
      about: {
        title: 'À propos de COMMA',
        placeholderBody:
          'Les données restent sur votre appareil. Récit complet et liens d’export en phase 2.',
      },
      print: {
        title: 'Impression',
        placeholderBody: 'Mises en page imprimables en phase 2 (`modules/reports/`).',
      },
      search: {
        title: 'Recherche',
        placeholderBody: 'Recherche floue en phase 2 (`modules/search/`).',
      },
    },
    ui: {
      modal: {
        close: 'Fermer',
      },
      confirm: {
        title: 'Confirmer ?',
        destructive: 'Cette action est difficile à annuler.',
        typeToConfirm: 'Tapez {value} pour confirmer',
      },
      toast: {
        success: 'Enregistré',
        error: 'Erreur',
        warning: 'Attention',
        info: 'Info',
        celebration: 'Bravo',
        dismiss: 'Ignorer',
      },
      fab: {
        addShift: 'Ajout rapide de quart',
        addExpense: 'Ajouter une dépense',
        addGoals: 'Objectifs',
        addSchedule: 'Ajouter au calendrier',
        endShift: 'Terminer le quart',
        openQuickActions: 'Actions rapides',
        quickActionsMenu: 'Menu d’actions rapides',
      },
      drawer: {
        close: 'Fermer',
      },
      progressRing: {
        label: 'Progrès',
      },
      skeleton: {
        loading: 'Chargement',
      },
      emptyState: {
        defaultTitle: 'Rien pour l’instant',
        defaultMessage: 'Ajoutez un élément ou modifiez les filtres.',
      },
      keypad: {
        title: 'Saisir un montant',
        confirm: 'OK',
        clear: 'Effacer',
        backspace: 'Retour arrière',
        open: 'Clavier',
      },
    },
  },
};

/**
 * @param {string} key dot notation, e.g. `shifts.addShift`
 * @param {'en'|'fr'} [lang='en']
 * @returns {string} never `undefined`; missing keys fall back to English then to `key`
 */
export function t(key, lang = 'en') {
  const parts = String(key).split('.').filter(Boolean);
  const walk = (root) => {
    let cur = root;
    for (const p of parts) {
      if (cur == null || typeof cur !== 'object') return null;
      cur = cur[p];
    }
    return typeof cur === 'string' ? cur : null;
  };
  const primary = walk(strings[lang] || strings.en);
  if (primary != null) return primary;
  if (lang !== 'en') {
    const fallback = walk(strings.en);
    if (fallback != null) return fallback;
  }
  return String(key);
}
